### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by Sogl** [VanOns/laraberg#1]
First of all, thank you for this project!

Do you have any plans to support Vue.js? As I can see, Gutenberg closely related to React.

**Comment by mauricewijnia** [comment]
Hi! Gutenberg is written with React, so there will probably not be a Vue.js version anytime soon.
However, as far as I am aware, there should not be anything preventing you from using this inside your Vue app. 

Are you having trouble getting it to work?

**Comment by Sogl** [comment]
No, just a question. I like how Gutenberg looks, but don't want React deps in my Vue project.

**Comment by mauricewijnia** [comment]
> So, I can mix them together?

Yes, as long as your target textarea is in the DOM it should show up perfectly fine :)

**Comment by AmirrezaNasiri** [comment]
I've made a Vuejs package for Laraberg editor. Just in case if anyone needed: https://github.com/evryn/laraberg-vue
