### ISSUE TITLE
Laraberg together with webpatser/laravel-uuid

### ISSUE THREAD

**Issue by kaymly** [VanOns/laraberg#10]
I'm using laravel-uuid,  contentable_id column is expecting integer id, is there a way to publish migration files from the vendor? 
Thanks,

**Comment by mauricewijnia** [comment]
The migration file is located at `vendor/van-ons/laraberg/src/database/migrations` so you could change it there. However I don't know about an easy way to change the polymorphic relation to use UUID's.

It may be easier to create a model yourself that uses integer id's and implements the Gutenbergable trait, and then make that model have a relation with your original model. Then you can access the Laraberg functions through your newly created model.

Hope this helps!
