### ISSUE TITLE
Removing unused widgets

### ISSUE THREAD

**Issue by Mamatlatomate** [VanOns/laraberg#100]
Hi,

It's more a question in the firts place than a feature request : 
There is a way to remove unused widget or limit to some widgets by default ?

I tried differents solutions but it's more the Wordpress way than Laraberg and it didn't works.
I found this issue (https://github.com/VanOns/laraberg/issues/18) but it didn't work for me.

I got this error : 
**Uncaught TypeError: window.wp.blocks.allowedBlockTypes is not a function**

Thanks a lot for your help

Mamat

**Comment by kevindierkx** [comment]
I've used the `removeBlockTypes` method:

```JS
document.addEventListener("DOMContentLoaded", () => {
    window.wp.data.dispatch('core/blocks').removeBlockTypes(blocks);
});
```

Where blocks is:

```JS
let blocks = [
    // WP Embeds...
    "core/embed",
    "core-embed/twitter",
    "core-embed/youtube",
    ...

    // WP Socials...
    "core/social-links",
    "core/social-link",
];
```
