### ISSUE TITLE
Laravel Filemanger Prefix Not Working Ignored

### ISSUE THREAD

**Issue by kinger251285** [VanOns/laraberg#102]
**Describe the bug**
I have added the prefix option to the laravel filemanager init however this gets ignored and laraberg when choosing media goes to the default laravel filemanager route.

**To Reproduce**
Try to upload any file via laraberg

.

**Environment (please complete the following information):**
- Laraberg Version: 1.1
 - OS: Ubuntu 18.04, LAMP
 - Browser - all Chrome safari firefox ie
 - Laravel Version: 6.18.23
 - Laravel filemanager version: 2.0

**Additional context**

My Laraberg vue.js component

`
    <  input  id="content" name="content" ></   input>

    export default {
    prop: ['value'],
      data () {
          return { content: '' }
      }, 

    methods: {
          

          larabergCreate () {

            Laraberg.init('content', {
            laravelFilemanager: { prefix: '/filemanager' },
            });

          },

    }, 

    created: function () {
        if (window.Laraberg.editor != null) {
            window.location.reload();
            // window.Laraberg.editor = null;
            // window.wp = null;
        }
    },   

    mounted: function () {

      setTimeout(() => this.larabergCreate(), 2300);
      },

    
    }
`

**Comment by MuhammadTaha** [comment]
add this to your route
```
Route::group(['prefix' => 'filemanager', 'middleware' => ['web','auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
```

**Comment by kinger251285** [comment]
> add this to your route
> 
> ```
> Route::group(['prefix' => 'filemanager', 'middleware' => ['web','auth']], function () {
>     \UniSharp\LaravelFilemanager\Lfm::routes();
> });
> ```

Still not working, still goes to - /laravel-filemanager?type=image

**Comment by kinger251285** [comment]
This seems to be working now.

However when i try to select the image it will not let me submit/select the image to be placed into laraberg

**Comment by MuhammadTaha** [comment]
I am having the same issue

**Comment by kinger251285** [comment]
Submission now working after deleting public/vendor/VanOns/Laraberg folder and running this command - php artisan vendor:publish --provider="VanOns\Laraberg\LarabergServiceProvider"

I can now submit images/files.

However i now have an issue with the absolute path, the domain is missing therefore images do not work.
