### ISSUE TITLE
Unable to confirm selected files

### ISSUE THREAD

**Issue by MuhammadTaha** [VanOns/laraberg#103]
I am using `laravel-filemanager`. When I try to confirm my selected images, it does nothing. No errors or anything. File manager is working fine with other editors.

I have added following code to my blade file:
```
Laraberg.init('content', { laravelFilemanager: {prefix :'/filemanager'} })
```
and my route looks like this:
```
Route::group(['prefix' => 'filemanager', 'middleware' => ['web','auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
```

**Expected behavior**
Select the image and show on the editor

**Screenshots**
![123](https://user-images.githubusercontent.com/4472580/86446755-adbc0f00-bd14-11ea-8ef6-4a918dd94976.png)

**Environment :**
- Laraberg Version: [1.1.1]
 - OS: [Ubuntu 18.04]
 - Browser [Chrome]
 - laravel  [5.8.38]
- unisharp/laravel-filemanager: [2.1.0]

**Comment by kinger251285** [comment]
Having the same issue!

Environment (please complete the following information):

Laraberg Version: 1.1
OS: Ubuntu 18.04, LAMP
Browser - all Chrome safari firefox ie
Laravel Version: 6.18.23
Laravel filemanager version: 2.0

**Comment by kinger251285** [comment]
Getting error:

filemanager?type=image:1386 Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by MuhammadTaha** [comment]
I am getting the following error when selecting images
![Screenshot from 2020-07-09 13-09-02](https://user-images.githubusercontent.com/4472580/87033236-2411b300-c1e6-11ea-9a30-0497fd1c6b12.png)

**Comment by MuhammadTaha** [comment]
Got it working by removing the existing old files of laraberg in `public/assets/laraberg` and installing it again which moved files from `assets` folder to `public/vendor` folder. 

"unisharp/laravel-filemanager": "2.1.0",
 "van-ons/laraberg": "1.1.1",

**Comment by kinger251285** [comment]
Above fixed for me too.

Now im having issues with the URL of the media not including the domain or being absolute.
