### ISSUE TITLE
Preview of custom blocks.

### ISSUE THREAD

**Issue by NikitaShkarubo** [VanOns/laraberg#106]
For custom blocks is impossible to make preview for html or append it as decoded html into editor.
Can you please fix it or describe how to do this?

**Comment by kevindierkx** [comment]
If you're talking about the small preview in the block sidebar, you can simply drop `example: {},` in the block config to get a preview.

More information: https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#example-optional

![Screenshot 2020-07-30 at 11 59 50](https://user-images.githubusercontent.com/2406615/88910244-76317b80-d25c-11ea-8662-a834b824712e.png)

**Comment by skacco** [comment]
I have the same problem.
In the editor I dont see the preview but the html code
  let title = 'Blocchi Globali'
        let slug = 'test'
        Laraberg.registerCategory(title, slug)
        const myBlock =  {
            title: 'My First Block!',
            icon: 'universal-access-alt',
            category: 'test',

            edit() {
                return "<h1>Hello editor.</h1>"
            },

            save() {
                return "<h1>Hello saved content.</h1>"
            }
        }
        Laraberg.registerBlock('my-namespace/my-block', myBlock)

When I click on the block i see "<h1>Hello saved content.</h1>

**Comment by kevindierkx** [comment]
@skacco 

> If you're talking about the small preview in the block sidebar, you can simply drop `example: {},` in the block config to get a preview.
> 
> 
> 
> More information: https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#example-optional
> 
> 
> 
> ![Screenshot 2020-07-30 at 11 59 50](https://user-images.githubusercontent.com/2406615/88910244-76317b80-d25c-11ea-8662-a834b824712e.png)
> 
>

**Comment by skacco** [comment]
sorry, no.
I mean that when I click on my custom block I see html code and not html preview `h1>Hello saved content.</h1>`

**Comment by kevindierkx** [comment]
@skacco Sorry, totally misread your comment...

Using the internal blocks should work, it should look something like this:

```js
// In your app.js
Laraberg.registerCategory('Custom', 'custom');
            Laraberg.registerBlock('vendor/custom-item', {
                title: 'Custom item',
                icon: 'align-none',
                category: 'custom',

                example: {},

                edit: (props) => {
                    return el(InnerBlocks, {
                        template: [
                            ['core/heading', {
                                content: 'New Item',
                                placeholder: 'Custom item',
                                level: 3,
                            }],
                            ['core/paragraph', {
                                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tempor condimentum arcu nec pretium.',
                                placeholder: 'Summary',
                            }],
                        ],
                        templateLock: 'all',
                    });
                },
                save: () => {
                    return el(InnerBlocks.Content);
                },
            });

```

**Comment by skacco** [comment]
Thank you but I receive javascript error
ReferenceError: el is not defined

**Comment by kevindierkx** [comment]
@skacco You need some reference to `wp.element.createElement` and `wp.blockEditor.InnerBlocks`, these are internal functions of the gutenberg editor. 

For example:

```js
var el = window.wp.element.createElement;
var InnerBlocks = window.wp.blockEditor.InnerBlocks;
```

I've also updated the code example in my previous comment.
