### ISSUE TITLE
Method to disable form leave confirmation?

### ISSUE THREAD

**Issue by mikebronner** [VanOns/laraberg#109]
When leaving an edited Gutenberg field, it pops open the warning: 

- Are you sure you want to leave this page? (Safari)
- This page is asking you to confirm that you want to leave - data you have entered may not be saved. (Firefox)
- etc.

From what I can tell the message is browser-dependent and triggered by the `window.onbeforeunload`. Unfortunately I haven found any reference to this in the code in Laraberg, so it must be in a dynamically loaded JS library that Gutenberg pulls in.

Any thoughts as to how we might go about disabling this? My use-case is that using the field in Vue and VueRouter doesn't actually trigger the warning until you navigate away from the SPA entirely. When switching "pages" within the SPA, it (as expected) doesn't detect that.

Thanks! :)

**Comment by Naroh091** [comment]
Gutenberg's `UnsavedChangesWarning` shows that warning. Ultimately we could generate our own version of Gutenberg with the alert disabled, but it would be interesting to make it customizable so we can disable the alert when clicking on some buttons (but still showing it if the user navigates away without saving changes). 

My JS experience is quite limited and Gutenberg is such a big project - I'll take a look but some help would be great.
