### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by RTC1** [VanOns/laraberg#11]
I noticed that the config allows the changing of the route path, but the routes are static within the JS (api-fetch.js).

Have forked for now.

**Comment by mauricewijnia** [comment]
Ye I haven't implemented that yet and I'm still thinking about how to do it.
Would you mind having to pass the route prefix to `initGutenberg`?

**Comment by RTC1** [comment]
Yea that's absolutely fine. 

Can you advise on the /wp/ calls? Can this work independently from WP?

**Comment by mauricewijnia** [comment]
I'm not sure if I understand what you mean.
The /wp/* calls are made by Gutenberg and get passed into `apiFetch` which then redirects them to the correct function call using regex. So no calls to any /wp/* urls are actually being made.

**Comment by RTC1** [comment]
Makes sense, I just spotted some calls in the console but no network request - hadn't seen the regex.

**Comment by mauricewijnia** [comment]
Implemented the custom prefix in api-fetch in version 0.0.3
