### ISSUE TITLE
alert on submit & restore history bugs

### ISSUE THREAD

**Issue by deanzod** [VanOns/laraberg#117]
**Describe the bug**
Bug 1. Every time you submit a new post an alert pops up warning that the data is not saved.
Bug 2. Every time you load the editor (after at least one save) it shows the 'restore' from browser option

**To Reproduce**
Both bugs are on the demo site:

BUG 1
1. Create an article
2. Click on submit
Popup alert

BUG 2
1. Create another article
Restore warning shown in large orange box

Are there any plans to fix these two bugs? I've noticed bug 2 has been mentioned a couple of times and someone submitted a 'fix' but it isn't really useful in most cases if there is no ID until after saving

**Comment by mdtanjilhasan** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/42772759/95156039-616ee800-07b7-11eb-93e2-0c8794f831a7.png)


This problem still exists. I hope it will be fixed soon.

**Comment by free4myself** [comment]
I have the same problem..

**Comment by SamehElalfi** [comment]
I think there is no official solution for this bug. So, you can open 'laraberg.js' file and search for `this.warnIfUnsavedChanges` then replace all results with `() => {}` . this will prevent the alert of submitting or refreshing the page.

and to remove the 'The backup of this post in your browser is different from the version below.' message, I removed the whole function (made it empty `function () {}`).

here is the laraberg.js file after making these two changes:

[laraberg.min.js.zip](https://github.com/VanOns/laraberg/files/5870117/laraberg.min.js.zip)

**Comment by free4myself** [comment]
> I think there is no official solution for this bug. So, you can open 'laraberg.js' file and search for `this.warnIfUnsavedChanges` then replace all results with `() => {}` . this will prevent the alert of submitting or refreshing the page.
> 
> and to remove the 'The backup of this post in your browser is different from the version below.' message, I removed the whole function (made it empty `function () {}`).
> 
> here is the laraberg.js file after making these two changes:
> 
> [laraberg.min.js.zip](https://github.com/VanOns/laraberg/files/5870117/laraberg.min.js.zip)

Thank you very much

**Comment by siva-neork** [comment]
Hi,
I tried replacing the js but getting JS error. Please help

laraberg.min.js:56 GET http://abc.com/laraberg/blocks 404 (Not Found)
(anonymous) @ laraberg.min.js:56
e.exports @ laraberg.min.js:56
e.exports @ laraberg.min.js:79
Promise.then (async)
r.request @ laraberg.min.js:79
r.<computed> @ laraberg.min.js:79
(anonymous) @ laraberg.min.js:56
(anonymous) @ laraberg.min.js:79
n @ laraberg.min.js:78
(anonymous) @ laraberg.min.js:78
e.<computed> @ laraberg.min.js:78
n @ laraberg.min.js:27
a @ laraberg.min.js:27
(anonymous) @ laraberg.min.js:27
(anonymous) @ laraberg.min.js:27
x @ laraberg.min.js:79
run @ laraberg.min.js:80
(anonymous) @ laraberg.min.js:80
(anonymous) @ laraberg.min.js:80
(anonymous) @ laraberg.min.js:80
(anonymous) @ laraberg.min.js:26
(anonymous) @ laraberg.min.js:26
j @ laraberg.min.js:26
(anonymous) @ laraberg.min.js:26
(anonymous) @ laraberg.min.js:26
(anonymous) @ laraberg.min.js:26
b @ laraberg.min.js:26
(anonymous) @ laraberg.min.js:21
n @ laraberg.min.js:73
(anonymous) @ laraberg.min.js:73
e.<computed> @ laraberg.min.js:73
r @ laraberg.min.js:27
a @ laraberg.min.js:27
Promise.then (async)
r @ laraberg.min.js:27
a @ laraberg.min.js:27
(anonymous) @ laraberg.min.js:27
(anonymous) @ laraberg.min.js:27
(anonymous) @ laraberg.min.js:21
FETCH_REUSABLE_BLOCKS @ laraberg.min.js:21
(anonymous) @ laraberg.min.js:35
(anonymous) @ laraberg.min.js:3
(anonymous) @ laraberg.min.js:4
(anonymous) @ laraberg.min.js:10
Qb @ react-dom.production.min.js:118
si @ react-dom.production.min.js:131
eb @ react-dom.production.min.js:132
Rg @ react-dom.production.min.js:144
Sc @ react-dom.production.min.js:158
Z @ react-dom.production.min.js:156
ah @ react-dom.production.min.js:159
xf @ react-dom.production.min.js:40
jquery.validate.min.js:132 

Uncaught TypeError: Cannot read property 'settings' of undefined
    at HTMLInputElement.b (jquery.validate.min.js:132)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.v.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at Object.simulate (jquery.min.js:3)
    at HTMLDocument.r (jquery.min.js:4)
    at laraberg.min.js:33
b @ jquery.validate.min.js:132
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
trigger @ jquery.min.js:3
simulate @ jquery.min.js:3
r @ jquery.min.js:4
(anonymous) @ laraberg.min.js:33
setTimeout (async)
(anonymous) @ laraberg.min.js:33
Qb @ react-dom.production.min.js:118
si @ react-dom.production.min.js:131
eb @ react-dom.production.min.js:132
hg @ react-dom.production.min.js:87
n @ laraberg.min.js:33
requestAnimationFrame (async)
i @ laraberg.min.js:33
2jquery.validate.min.js:132 

Uncaught TypeError: Cannot read property 'settings' of undefined
    at HTMLInputElement.b (jquery.validate.min.js:132)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.v.handle (jquery.min.js:3)
b @ jquery.validate.min.js:132
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
jquery.validate.min.js:132 

Uncaught TypeError: Cannot read property 'settings' of undefined
    at HTMLInputElement.b (jquery.validate.min.js:132)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.v.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at Object.simulate (jquery.min.js:3)
    at HTMLDocument.r (jquery.min.js:4)
b @ jquery.validate.min.js:132
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
trigger @ jquery.min.js:3
simulate @ jquery.min.js:3
r @ jquery.min.js:4
jquery.validate.min.js:350 

Uncaught TypeError: Cannot read property 'replace' of undefined
    at a.validator.escapeCssMeta (jquery.validate.min.js:350)
    at a.validator.errorsFor (jquery.validate.min.js:344)
    at a.validator.prepareElement (jquery.validate.min.js:251)
    at a.validator.element (jquery.validate.min.js:166)
    at a.validator.onfocusout (jquery.validate.min.js:88)
    at HTMLElement.b (jquery.validate.min.js:133)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.v.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at Object.simulate (jquery.min.js:3)
escapeCssMeta @ jquery.validate.min.js:350
errorsFor @ jquery.validate.min.js:344
prepareElement @ jquery.validate.min.js:251
element @ jquery.validate.min.js:166
onfocusout @ jquery.validate.min.js:88
b @ jquery.validate.min.js:133
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
trigger @ jquery.min.js:3
simulate @ jquery.min.js:3
r @ jquery.min.js:4
22laraberg.min.js:42 

Uncaught TypeError: Cannot read property 'calculateSize' of undefined
    at p.value (laraberg.min.js:42)
    at laraberg.min.js:42
    at c (laraberg.min.js:1)
    at so (laraberg.min.js:2)
    at e.value (laraberg.min.js:42)

**Comment by siva-neork** [comment]
> I think there is no official solution for this bug. So, you can open 'laraberg.js' file and search for `this.warnIfUnsavedChanges` then replace all results with `() => {}` . this will prevent the alert of submitting or refreshing the page.
> 
> and to remove the 'The backup of this post in your browser is different from the version below.' message, I removed the whole function (made it empty `function () {}`).
> 
> here is the laraberg.js file after making these two changes:
> 
> [laraberg.min.js.zip](https://github.com/VanOns/laraberg/files/5870117/laraberg.min.js.zip)

I replace the file shared but getting JS error, please help

**Comment by xvital** [comment]
Any update on this issue?
