### ISSUE TITLE
Full screen mode show Wordpress Icon

### ISSUE THREAD

**Issue by Sartoric** [VanOns/laraberg#118]
**Describe the bug**
Selecting Full screen mode, the Wordpress Icon is shown in the toolbar and it's linked to ""edit.php?post_type=page"

**To Reproduce**
Select full screen mode 

I manage to hide it via css 
`.components-button.edit-post-fullscreen-mode-close.has-icon{
    display: none;
    visibility: hidden;
}`

Maybe fullscreen mode could be removed from the list as it doesn't seem to go fulscreen 😁

**Comment by mauricewijnia** [comment]
Thanks for reporting!

Right now we're working on a complete rebuild of the Laraberg Javascript codebase.
This will give us more control over the functionality that we add to the editor, so when that is done this will certainly be fixed!
