### ISSUE TITLE
Render blocks by blade templates(x-components)

### ISSUE THREAD

**Issue by efolam** [VanOns/laraberg#122]
**Is your feature request related to a problem? Please describe.**
nothing

**Describe the solution you'd like**
I made a few blocks and I want to render them through the blade templates(x-components), is there such a possibility in this package?

**Describe alternatives you've considered**
tried using `renderBlocks()` in `"laraberg/src/Helpers/BlockHelper.php"`

**Additional context**
Laraberg Editor return this for my custom blocks:
```
<!-- wp:custom/container {"options":{"type":"full-width"}} -->
  <!-- wp:custom/container {"options":{"type":"default"}} -->
    <!-- wp:custom/spacer {"type":"default"} /-->
    <!-- wp:paragraph --> <p>Lorem ipsum dolor sit amet</p><!-- /wp:paragraph -->
    <!-- wp:custom/spacer {"type":"middle"} /-->
  <!-- /wp:custom/container -->
<!-- /wp:custom/container -->

<!-- wp:paragraph --> <p>Lorem ipsum</p> <!-- /wp:paragraph -->
```

Container & Spacer - my custom blocks
Paragraph - default Gutenberg block

**Comment by mauricewijnia** [comment]
Hi!

Currently blocks are rendered only in Javascript, so this is not possible right now.

We are slowly working towards a better foundation for Laraberg, and dynamic (php) blocks will be a part of that in the future.
So hopefully we can make blade template works for that!

**Comment by galpratama** [comment]
Is there any update for dynamic blocks? I think this is important feature for many of us @mauricewijnia

**Comment by mauricewijnia** [comment]
@galpratama Sorry no update for dynamic blocks...

I've got some time for Laraberg in the coming weeks, the goal then is to rewrite the javascript frontend so we have a more solid foundation for any future development.

I definitly want to add dynamic blocks, but sadly I just don't have the time to do it right now. After the javascript rewrite I'll definitly look into that. And, ofcourse, I'll consider a pull request that implements it!

**Comment by efolam** [comment]
Resolved
You can use this solution for parse block data https://github.com/VanOns/laraberg/issues/123
Next send received data to simple render component like this:

blocks/render.blade.php:
```
@foreach ($blocks as $block)
    @if (strpos($block['blockName'], 'blocks/') === false)
        {!! $block['innerHTML'] !!}
    @else
        @php
        $blockName = str_replace('blocks/', 'components.blocks.', $block['blockName']);
        @endphp

        @component($blockName, $block['attrs'])
            @if (!empty($block['innerBlocks']))
                <x-blocks.render :blocks="$block['innerBlocks']" />
            @endif
        @endcomponent
    @endif
@endforeach
```

$blockName - name laraberg core or custom block, and it should be equal blade file name
