### ISSUE TITLE
Parsing the content returned by laraberg

### ISSUE THREAD

**Issue by efolam** [VanOns/laraberg#123]
**Is your feature request related to a problem? Please describe.**
Laraberg returns content as HTML, I need it to return it as an array of blocks.

**Describe the solution you'd like**
It would be nice if the WP_Block_Parser class could be used in your solution.

**Describe alternatives you've considered**
I copied the `WP_Block_Parser`, `WP_Block_Parser_ Block` and `WP_Block_Parser_Frame` classes to Laravel and used this way:
```
...
use App\Classes\BlocksParser\WP_Block_Parser;

class PagesController extends Controller
{
  ...

  public function show(Page $page)
  {
    $parser = new WP_Block_Parser;

    return view('pages.show', [
      'page' => $page,
      'blocks' => $parser->parse($page->laraberg_content)
    ]);
  }

  ...
}
```
Now block content is parsed by wordpress itself and returns an array of blocks.
Supports block nesting

**Additional context**
![2020-12-09 10 44 10](https://user-images.githubusercontent.com/57411955/101599849-811aca80-3a0b-11eb-884b-63014754e993.jpg)

Classes are found along this path in wordpress:
wp-includes/class-wp-block-parser.php

[class-wp-block-parser.php.zip](https://github.com/VanOns/laraberg/files/5664237/class-wp-block-parser.php.zip)

**Comment by mauricewijnia** [comment]
Hi!

Thanks for your issue!

Is there any reason why this should be included in Laraberg?
It seems to me like your current solution is working fine for your purposes.
And to be honest, I'm not really a fan of having to manually check and update some WP Core code with every WP release.
