### ISSUE TITLE
MediaUpload component is not work

### ISSUE THREAD

**Issue by efolam** [VanOns/laraberg#126]
**Describe the bug**
When i click on the `MediaUpload` component i have this error:
![2021-01-27 18 01 20](https://user-images.githubusercontent.com/57411955/106009703-ae116280-60c9-11eb-8c98-a3f20aab35b0.jpg)

**To Reproduce**
1. Go to laraberg editor
2. Click `MediaUpload` component in custom block (on `core/image` it work normally, bug only on custom block)
3. See error in console

**Expected behavior**
Expected open `laraberg-filemanager` interface after click on `MediaUpload` button, like `core/image` block

**Screenshots**

**Environment (please complete the following information):**
- Laraberg Version: [1.1.1]
 - OS: [macOS Big Sur, macOS Catalina, Windows]
 - Browser [chrome, safari]

**Additional context**
```
<MediaUpload
    value={ mediaId }
    onSelect={ data => {
        console.log('selected')
    }}
    render={ ({ open }) => (
        <Button
            isPrimary
            onClick={ open }
        >Выбрать</Button>
    ) }
/>
```

How can i use `MediaUpload` component with Laravel File Manager in custom blocks

**Comment by efolam** [comment]
I looker at your code, how you replaced a `editor.MediaUpload` component to `LaravelFilemanager` component by hook.
```
hooks.addFilter(
  'editor.MediaUpload',
  'core/edit-post/components/media-upload/replace-media-upload',
  () => LaravelFilemanager
)
```

It doesn't work for MediaUpload in custom block.
May be i should open `Laravel Filemanager` in custom blocks directly, without `MediaUpload` component? But i can't understand how do it.

**Comment by igramnet** [comment]
Hi, @efolam did u fix it? I can't upload files by laraberg.
![image](https://user-images.githubusercontent.com/15707768/189497017-6d35670e-f992-401a-bc47-4b1ade835a9d.png)

`<script>
    Laraberg.init('text', { laravelFilemanager: true })
</script>`

**Comment by ArtMin96** [comment]
@igramnet try
```javascript
const mediaUploaded = ({filesList, onFileChange}) => {}

Laraberg.init('laraberg__editor', {
    mediaUpload: mediaUploaded
})
```
