### ISSUE TITLE
Still maintained? 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [VanOns/laraberg#132]
Is this still being maintained? It looks like there hasn't been a new release in almost a year.

**Comment by mauricewijnia** [comment]
Hi!

There's a lot of work done to rewrite the JS part of the project to be standalone.
When I get some time to finish that there'll be an update, but for now it looks like we have to be patient...

**Comment by selected-pixel-jameson** [comment]
Thanks for letting me know. Was just curious.
