### ISSUE TITLE
Tools > Manage All Reusable Blocks doesn't work

### ISSUE THREAD

**Issue by Sartoric** [VanOns/laraberg#14]
Clicking the 3 dots menu > Tools > Manage All Reusable Blocks the following query string is appended to the current url "?post_type=wp_block"

Is it somehow "expected" or can it be filed as a bug ? 
Tnx

**Comment by mauricewijnia** [comment]
I'm not planning to implement a specific page for managing the reusable block since in Wordpress it is an independent admin page. Blocks can also be updated and removed from the Gutenberg editor itself, so for now that seems fine.

I will hide hide the links to the reusable blocks management page in a future release, thanks for reporting!

**Comment by Sartoric** [comment]
Hi @mauricewijnia 
Thanks for the changes.

I've updated the module and run the publish again, but it seems that the removeBlockManagement doesn't work properly.
at least on 
- Chrome 74.0.3729.157
- Firefox 66.0.5
- Safari 12.1.1

Am I missing something ?

**Comment by mauricewijnia** [comment]
If you're on v0.0.5 it should work. Atleast on [the demo](http://demo.laraberg.io/articles/create) it's fine.
Maybe you have to refresh the page cache or maybe you have to rebuild your own JS and CSS assets?
If that does not work can you show me a screenshot of where you're still seeing the link to block management?

**Comment by Sartoric** [comment]
Hi @mauricewijnia 
Yes I'm on 0.0.5. 
I've cleaned project cache and view cache too.
I've run the publish again with the force flag.
Tested on "anonymous" browser mode
I don't see any error in console 

I did I quick check and it seems that at least the laraberg.css from public/css is not published in project public/vendor 

Screenshot attached

![settings](https://user-images.githubusercontent.com/6607379/58094332-b618bf80-7bd0-11e9-8fd2-fc647668ce38.png)

**Comment by mauricewijnia** [comment]
Hmm looks like I have the same issue on my local environment, but not on the demo environment...
Thanks for the heads up I'll reopen the ticket!

**Comment by mauricewijnia** [comment]
I think this should be fixed in 0.0.6, but I'm not sure why it was an issue in the first place.
Let me know if it's still an issue!

**Comment by Sartoric** [comment]
Just tried, but I still have the issue. 
I've seen that publish is in fact not publishing anything, even if it says it did.

Tried force and tag just to test it 
php artisan vendor:publish --force --provider='VanOns\Laraberg\LarabergServiceProvider' --tag=public
php artisan vendor:publish --force --provider='VanOns\Laraberg\LarabergServiceProvider' --tag=config

cleaned composer cache , artisan caches ... no way. 
I'll check later if there something going wrong in this project.

**Comment by Sartoric** [comment]
For everyone knowledge, I've found the problem. 
I'm using PhPstorm and running vendor:publish from its CL tool Console.
I didn't really notice the apostrophe in provider name that was in fact the problem as the provider wasn't recognized. Removing it, solved the publish problem  and the "menu issue" too.

Thanks

**Comment by mauricewijnia** [comment]
Oh wow, I'm glad you managed to fix it.
I'll update the readme to use quote marks instead of apstrophes to make it a bit more clear.
