### ISSUE TITLE
Upgrade from 1.1.1 to 2.0.0

### ISSUE THREAD

**Issue by ajotka** [VanOns/laraberg#150]
**Describe the bug**
Hi, I would love to upgrade version 1.1.1 to 2.0.0-rc12 (I need Dynamic Block for news), but readme is not updated.
After upgrade I have an error that Gutenbergable doesn't exist, and also getRawContent() method. 

So my question is, how can i replace this model and this method?

**Comment by Stuart92** [comment]
In case you require further information, it is available here: https://github.com/VanOns/laraberg/releases/tag/v2.0.0

**Comment by mauricewijnia** [comment]
Upgrade instructions have been provided on the release page, hopefully that is enough to get you through it. If not please reply to this issue again :)
