### ISSUE TITLE
Demo site (demo.laraberg.io) doesn't appear to work

### ISSUE THREAD

**Issue by jamesmcroft** [VanOns/laraberg#156]
**Describe the bug**

Currently, it doesn't seem possible to visualise this as the [demo site](http://demo.laraberg.io/) doesn't appear to be loading correctly.

**Comment by mauricewijnia** [comment]
Hi, that's right. We shut down the demo site because people were not behaving and I do not want to spend time moderating it. Sorry for the inconvenience!
