### ISSUE TITLE
Color and Background issue

### ISSUE THREAD

**Issue by Templemitra** [VanOns/laraberg#161]
first of all thanks for the great work.
I am facing some issues. Text color and background are not showing even though I used the sidebar: true they are still not showing in new 2.0.

please check and suggest to me:
   const options = { 
            colors: [{
                    color: '#ffffff',
                    name: "White",
                    slug: 'white'
                },
                {
                    color: '#000000',
                    name: "Black",
                    slug: 'black'
                },
                {
                    color: '#ff0000',
                    name: 'Red',
                    slug: 'red'
                },
                {
                    color: '#00ff00',
                    name: 'Green',
                    slug: 'green'
                },
                {
                    color: '#0000ff',
                    name: 'Blue',
                    slug: 'blue'
                },
            ],
            sidebar: true,
        }
        Laraberg.init('content', options)

**Comment by Jacotheron** [comment]
You might want to look at my reply to my own issue at [Issue 160](https://github.com/VanOns/laraberg/issues/160#issuecomment-1239172129).

I went through all the files, compiled a developer version etc to see how it all works, as I was also having this issue.
