### ISSUE TITLE
Laraberg not loading and has Javascript error

### ISSUE THREAD

**Issue by joshuacadman01** [VanOns/laraberg#165]
I am in the process of setting up a CMS with Laravel and saw about Laraberg. I have followed the instructions to integrate this into my Laravel site, however I am getting a few issues when trying to get this to work.

When loading the page, I am getting the following errors:
![Screenshot 2022-08-02 at 04 40 07](https://user-images.githubusercontent.com/74733356/182286817-933b52e4-b353-411b-bdfe-2621d1f45031.png)

My current code is:
`<link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
<script src="{{asset('vendor/laraberg/js/laraberg.js')}}"></script>
<script src="https://unpkg.com/react@17.0.2/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js"></script>
...
<textarea id="laraberg" name="[laraberg]" hidden></textarea>
...
<script type="text/javascript">

            if (document.readyState !== 'loading') {
                console.log('document is already ready, just execute code here');
                myInitCode();
            } else {
                document.addEventListener('DOMContentLoaded', function () {
                    console.log('document was not ready, place code here');
                    myInitCode();
                });
            }

            function myInitCode() {
                Laraberg.init('laraberg');
            }

        </script>
`

I am running Laravel using Docker on Mac

When I load the page, this is what is loading. Under the 'Post Content' tab, is where the textarea is placed.
![Screenshot 2022-08-02 at 04 43 56](https://user-images.githubusercontent.com/74733356/182287232-783ace9a-e523-4277-b139-fb2adef2309e.png)
.

**Comment by ArtMin96** [comment]
Hi @joshuacadman01. Have you found a solution?

**Comment by joshuacadman01** [comment]
@ArtMin96 I never found the solution to this and just moved away from Laraberg and onto TinyMce.

**Comment by ArtMin96** [comment]
@joshuacadman01 I have found the solution. Add the scripts in this order

```html
<script src="https://unpkg.com/react@17.0.2/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/moment@2.24.0/min/moment.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{{asset('vendor/laraberg/js/laraberg.js')}}"></script>
```
