### ISSUE TITLE
 Integrate my own file manager

### ISSUE THREAD

**Issue by shaunluedeke** [VanOns/laraberg#166]
Hi is there a possibility that my own file manager is integrated via javascript?

**Comment by shaunluedeke** [comment]
![Screen](https://user-images.githubusercontent.com/77498048/185351126-097f0e4b-2ffc-4205-9d56-8fe2315acd3a.PNG)

**Comment by igramnet** [comment]
Hi, @shaunluedeke  how do you add a feature "Upload"?
