### ISSUE TITLE
Fatal Error when changing the $contentColumn property on model

### ISSUE THREAD

**Issue by andrewdmaclean** [VanOns/laraberg#174]
**Describe the bug**
When following the instructions in the README to change the $contentColumn property on model, I am presented with the error:
`App\Models\[MyModel] and VanOns\Laraberg\Traits\RendersContent define the same property ($contentColumn) in the composition of App\Models\[MyModel]. However, the definition differs and is considered incompatible. Class was composed.`

**To Reproduce**
1. Select a Model
2. Add the following to said Model
```
use VanOns\Laraberg\Traits\RendersContent;

class MyModel extends Model {
  use RendersContent;

  protected $contentColumn = 'my_column';
}
```
3. See error

**Expected behavior**
No error and able to use $model->render() as outlined.

**Environment (please complete the following information):**
- Laraberg Version: [e.g. 1.0.0]
 - OS: Windows 10
 - Browser: Firefox
 - Version:106.0.1

**Temporary Fix**
I have added the following constructor which seems to fix the issue but seems a bit... hacky.

```
   public function __construct()
     {
          $this->contentColumn = 'my_column';
     }
```

**Comment by arman-arif** [comment]
I got the same issue with the $contentColumn property
Cannot redeclare VanOns\Laraberg\Traits\RendersContent::render()
