### ISSUE TITLE
Patterns and translations

### ISSUE THREAD

**Issue by xpalko** [VanOns/laraberg#178]
Hi,
I have a question about how to use patterns from wordpress (Call to Action, Pricing Table, etc.) in Laraberg and also how to add translations (German, Czech, ...)?
Maybe just a example would be enough.
Thank you
Pavel Kaspar

**Comment by xpalko** [comment]
@ArtMin96 Hi. I've already solved both the localization and patterns issues, but now I can't figure out how to use a custom Media Library/Upload without Wordpress dependencies. Some idea?

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/media-upload/README.md

doesn't work for me (probably not the whole code, just a hint).

**Comment by ArtMin96** [comment]
@xpalko Can you show an example of how you did it?

Try this for media.

```javascript
const mediaUpload = ({filesList, onFileChange}) => {}

Laraberg.init('element', {
    mediaUpload,
    //...
})
```

**Comment by xpalko** [comment]
@ArtMin96 Thanks a lot, I'll give it a try. As for localization and patterns, I implemented it in a similar Automattic/isolated-block-editor project, but the code could definitely be used for Laraberg as well. I hope to try it soon!
In more detail it is https://github.com/xpalko/isolated-block-editor/commits/trunk, commits on Jan 5, 2023

**Comment by ArtMin96** [comment]
@xpalko Thanks. When you get the patterns in laraberg can you share?
