### ISSUE TITLE
Embeds doesn't work on frontend 

### ISSUE THREAD

**Issue by anmolko** [VanOns/laraberg#179]
I have recently tried laraberg as my editor and everything works like a charm in backend. No Issues.
But I tired embedding youtube videos or vimeo or twitter or any other kind of embeds and it works in backend but in frontend it just doesn't render anything except the URL I just embeded.

You can easily reproduce this by embedding anything like a youtube video or twitter post on your backend and in
frontend it doesn't render. 
 
This is the backend of the laraberg editor where youtube and twitter posts are embeded and it works.
![Screen Shot 2023-01-04 at 16 34 35](https://user-images.githubusercontent.com/76039830/210539459-419bba8b-10c7-4a6a-8c49-83b60106480c.png)

And this is the frontend where it just shows the link.
![Screen Shot 2023-01-04 at 16 34 42](https://user-images.githubusercontent.com/76039830/210539655-871a6a58-a9d2-4d9a-a7dc-47d6fda4a907.png)

This is how the html code looks when you inspect it:
![Screen Shot 2023-01-04 at 16 37 37](https://user-images.githubusercontent.com/76039830/210539918-b38c60a3-9591-4955-b294-d7b1c4378f5c.png)

Any help?

**Comment by anmolko** [comment]
Help, anyone?

**Comment by webinn** [comment]
Your code examples shows that you have not run the render() method. 
I have not tested this myself, but what happens after $model->render('my_column');  ?
