### ISSUE TITLE
register custom categories

### ISSUE THREAD

**Issue by ArtMin96** [VanOns/laraberg#180]
**Is your feature request related to a problem? Please describe.**
...

**Describe the solution you'd like**
...

**Describe alternatives you've considered**
...

**Additional context**
How can I register custom categories? I looked for the `registerCategories` function in all options from 'WordPress exports' section but did not find it. Also, can you open the discussion section so that we don't create a new issue for questions or discussions?

**Comment by AndreiTelteu** [comment]
I found a way to do this:

```js
const { blocks } = window.Laraberg.wordpress;
blocks.setCategories([
    ...(blocks.getCategories() || []),
    { title: 'My custom category', slug: 'my-custom' },
]);
```

If you prefer ES5, older javascript:

```js
var categories = window.Laraberg.wordpress.blocks.getCategories() || [];
categories.push({ title: 'My custom category', slug: 'my-custom' });
window.Laraberg.wordpress.blocks.setCategories(categories);
```

**Comment by ArtMin96** [comment]
@AndreiTelteu Already got this:
```javascript
registerCategory(title, slug) {
    const { dispatch, select } = this.data

    let category = {
        slug: slug,
        title: title
    }

    const currentCategories = select('core/blocks')
        .getCategories()
        .filter(item => item.slug !== category.slug)

    dispatch('core/blocks')
        .setCategories([
            ...(currentCategories || []),
            category
        ])
}
```

Thanks
