### ISSUE TITLE
Uncaught TypeError: Laraberg.setContent is not a function

### ISSUE THREAD

**Issue by ArtMin96** [VanOns/laraberg#181]
**Describe the bug**
Uncaught TypeError: Laraberg.setContent is not a function

**To Reproduce**
1. Just call `Laraberg.setContent('some content')`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Laraberg Version: [2.0.3]
 - OS: [Linux  mint (cinnamon)]
 - Browser [chrome]
 - Version [e.g. 22] version for what?

**Additional context**
Thanks for amazing package

**Comment by AndreiTelteu** [comment]
I found the solution:

```jsx
const { dispatch } = window.Laraberg.wordpress.data;
const { parse } = window.Laraberg.wordpress.blocks;

window.Laraberg.setContent = (input) => {
    dispatch('block-editor').setBlocks(parse(input));
};
```

Now simply call 
```js
window.Laraberg.setContent('<!-- wp:paragraph --> <p>dada</p> <!-- /wp:paragraph -->');
```
If your input does not have those comments `<!-- wp:paragraph -->` they will appear as unknown blocks.

**Comment by ArtMin96** [comment]
Thanks. It works
