### ISSUE TITLE
Switch package license to MPL

### ISSUE THREAD

**Issue by binaryfire** [VanOns/laraberg#182]
Hi guys

Gutenberg is now dual licensed and can be used under a GPL or MPL license: https://github.com/WordPress/gutenberg/blob/trunk/LICENSE.md

This was done to encourage wider user of Gutenberg in other apps. Technically any GPL package added to an app makes the entire app’s source code fall under the GPL. Many enterprises are careful to avoid GPL dependencies for that reason.

Would you be able to switch this package’s license to MPL? We’d like to try it in a closed-source commercial application

**Comment by mauricewijnia** [comment]
Hi, that's great news!

Sadly I don't think it's possible to just switch the license, for that we would need the permission of all contributers, and we're not in contact with them.
