### ISSUE TITLE
Text color or Background color not working

### ISSUE THREAD

**Issue by Templemitra** [VanOns/laraberg#183]
I try too many times to solve the color problem but not solve it. please suggest to me what I am doing wrong. 
const options = {
            height: "500px", // OK
            alignWide: true, //OK
            customTextColor: true,
            customBackgroundColor: true,
            customGradient: true, 
            supportsLayout: true, //OK
            'colors' => [
                [
                    'name' => 'White',
                    'slug' => 'white',
                    'color' => '#ffffff',
                ],
                [
                    'name' => 'Black',
                    'slug' => 'black',
                    'color' => '#000000',
                ],
                [
                    'name' => 'Cyan bluish gray',
                    'slug' => 'cyan-bluish-gray',
                    'color' => '#abb8c3',
                ],
                [
                    'name' => 'Pale pink',
                    'slug' => 'pale-pink',
                    'color' => '#f78da7',
                ],
                [
                    'name' => 'Vivid red',
                    'slug' => 'vivid-red',
                    'color' => '#cf2e2e',
                ],
                [
                    'name' => 'Luminous vivid orange',
                    'slug' => 'luminous-vivid-orange',
                    'color' => '#ff6900',
                ],
                [
                    'name' => 'Luminous vivid amber',
                    'slug' => 'luminous-vivid-amber',
                    'color' => '#fcb900',
                ],
                [
                    'name' => 'Light green cyan',
                    'slug' => 'light-green-cyan',
                    'color' => '#7bdcb5',
                ],
                [
                    'name' => 'Vivid green cyan',
                    'slug' => 'vivid-green-cyan',
                    'color' => '#00d084',
                ],
                [
                    'name' => 'Pale cyan blue',
                    'slug' => 'pale-cyan-blue',
                    'color' => '#8ed1fc',
                ],
                [
                    'name' => 'Vivid cyan blue',
                    'slug' => 'vivid-cyan-blue',
                    'color' => '#0693e3',
                ],
                [
                    'name' => 'Vivid purple',
                    'slug' => 'vivid-purple',
                    'color' => '#9b51e0',
                ],
            ],
            fontSizes: [{
                name: 'small',
                size: 12
            }, {
                name: 'normal',
                size: 14
            }, {
                name: 'large',
                size: 16
            }, {
                name: 'huge',
                size: 18
            }], //OK
 }
        Laraberg.init('content', options);

**Comment by webinn** [comment]
What is not working? Have you added the color classes in your style? 
Eg
`.has-black-color{
                    color:#000000;
  }`

**Comment by Templemitra** [comment]
> .has-black-color{ color:#000000; }

thank you
