### ISSUE TITLE
Drag'n'Drop doesn't work in "media" Block

### ISSUE THREAD

**Issue by Sartoric** [VanOns/laraberg#19]
Trying to drag an image, video or audio inside the block generate api error 
"API handler not found. /wp/v2/media"

Blocks involved (tested)
- Gallery
- Image
- Video
- Audio 
- Cover
- File

**Comment by mauricewijnia** [comment]
This is kind of expected since media upload functionality is not handled by Laraberg itself.
Currently I'm planning to extend the amount of filemanager plugins that can be used with Laraberg, this means that the drag & drop behaviour has to be implemented for all of those.

Laravel Filemanager offers its own drag & drop functionality in it's popup window and I can imagine that most other filemanagers will have this aswell.

So unless it's a small amount of work, which I don't expect, I feel like it's not worth it to implement drag & drop anytime soon.

I'll probably either remove the drag & drop functionality completely, or show a more descriptive error message that it's not supported.

**Comment by Sartoric** [comment]
Agree.
In fact I supposed it was somehow expected but I reported it just to list it.

I really appreciate your porting, so since I'm using it, just let me know if you need an hand. I'll try to help

**Comment by mauricewijnia** [comment]
You're already helping a lot with creating those issues, so thanks!
Also, if you have any ideas or feedback about the current implementation and how to improve it you can let me know!

**Comment by mikebronner** [comment]
I ran into this issue as well. I wonder what it would take to implement the end-point `/wp/v2/media` so that drag-and-drop would work? I'm not a huge fan of the filemanager popup window, and also the message to the user to drag-and-drop is misleading. So at the very least the message would need to be changed, and the drag-and-drop functionality disabled, for this to be usable by the general users of a site. (Just thinking out loud, not trying to put pressure on @mauricewijnia.) :)

**Comment by mauricewijnia** [comment]
It's not that hard to implement the endpoint and let it upload files to some folder.
I'm not really familiar with the Laravel filesystem though, so I'm not sure how difficult it is to implement this in a way that's safe and easily configurable for stuff like multi-user uploads and authorization...

Until then the drag and drop should be disabled or atleast display a message that it's not supported :)

**Comment by mikebronner** [comment]
I have disabled the drag-and-drop functionality and messaging using CSS, this might help others as well:
```css
.components-drop-zone,
.components-form-file-upload,
.editor-media-placeholder .components-placeholder__instructions {
    display: none;
    pointer-events: none;
}
```

Please do let me know if anyone finds any issues with this solution.

**Comment by mauricewijnia** [comment]
The css solution no longer works since the same element is used to give the user feedback when dragging and dropping blocks. I've added a message notifying the user that drag & drop uploading is not supported right now. 

I do want to implement this in the future though!

**Comment by Sartoric** [comment]
@mauricewijnia 
Are you referring to the RC version ? 
Because I've just updated it and it seems that css trick still works (while I don't see any messages if I drag an image into an image block)

**Comment by mauricewijnia** [comment]
It does work, but I believe that it also hides the blue border that indicates where you can drag & drop other blocks right?
![image](https://user-images.githubusercontent.com/8679682/62215052-7aeff500-b3a6-11e9-9992-dfcab940eeb1.png)

**Comment by Sartoric** [comment]
Oh, ok I see now.

But where should be displayed the message you've added ? Inside the dnd area ? 
If I drag something I see the old errors

![Schermata 2019-07-31 alle 15 14 44](https://user-images.githubusercontent.com/6607379/62216105-74627d00-b3a8-11e9-9c19-d99d3d9bb16e.png)

**Comment by mauricewijnia** [comment]
Did you run `php artisan vendor:publish --provider="VanOns\Laraberg\LarabergServiceProvider" --tag="public" --force` after updating?

It should display a message like this
![image](https://user-images.githubusercontent.com/8679682/62216403-f94d9680-b3a8-11e9-9f43-86b6efc55016.png)

You can see it on the demo site as well http://demo.laraberg.io/articles/create

**Comment by kayastha1988** [comment]
Gallery only showing one image and is not editable.

When adding a gallery block, I can not select multiple images from the laravel filemanager. In the editor only the sinle image is shown.

Is there any possibility to hide/remove Gallery icon from editor since its not worth it to implement??? How I can remove that icon from editor?

Thanks in advance.

**Comment by Munzambi-Miguel** [comment]
Hello, my greetings
I'm using laraberge, my difficulty is in the media part

can i create the upload function

const mediaUpload = ({filesList, onFileChange}) => {
            setTimeout(() => {
                const uploadedFiles = Array.from(filesList).map(file => {


                    var dataUrls = $.post('{{ route('sendimage') }}', {
                        file: 'file',
                        _token: '{{ csrf_token() }}'
                    }).done(function (res) {
                        return res.img
                    })

                    console.log(dataUrls)

                    return {
                        id: file.name,
                        name: file.name,
                        url: dataUrls
                    }
                })
                onFileChange(uploadedFiles)
            }, 1000)
        }
        Laraberg.init('[id_here]', {
            mediaUpload: mediaUpload,
            imageEditing: true,
            supportsLayout: true
        })


I tried this way but it didn't work

**Comment by Munzambi-Miguel** [comment]
Hi guys, I managed to get around this way
I don't know if this is correct, but it worked.
in my project


**"In my blede file in the scripts I put this function"**
 const mediaUpload = ({filesList, onFileChange}) => {
            setTimeout(async () => {

                let data = new FormData;
                Array.from(filesList).map(file => {
                    data.append('ficheiro', file);
                });

                const information = await axios.post("{{ route('sendimage') }}", data, {
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}',
                        'Content-Type': 'multipart/form-data'
                    }
                }).then(function (response) {
                    console.log(response.data)
                    return response.data.msg;
                })


                const uploadedFiles = Array.from(filesList).map(file => {
                    console.log(file)
                    return {
                        id: file.id,
                        name: file.name,
                        url: information
                    }
                })

                onFileChange(uploadedFiles)
            }, 1000)
        }
        Laraberg.init('[id_here]', {
            mediaUpload: mediaUpload,
            imageEditing: true,
            supportsLayout: true
        })


In the controller create a function that receives the file and returns the path where it is stored
controller file

public function uploading(Request $request)
{

        $path = 'app/public/editor_laraberge';
        $file = $request->hasFile('ficheiro') ? $request->file('ficheiro') : null;
        $new_image_name = 'editor' . date('Ymd') . uniqid('', true) . '.jpg';
        $upload = $file->move(storage_path($path), $new_image_name);

        return response()->json(['msg' => "storage/editor_laraberge/" . $new_image_name, 'file' => $file, 'request' => $request]);

}
