### ISSUE TITLE
Request: demo 

### ISSUE THREAD

**Issue by gavinhewitt** [VanOns/laraberg#2]
Would be nice to have a demo page. Yes, I know that you can check out Gutenberg on Wordpress but personally I would like to see a Laravel powered demo.

Goed werk mannen!

**Comment by mauricewijnia** [comment]
I'm definitely planning to make a demo-site somewhere in the upcoming weeks!

**Comment by mehranabi** [comment]
Hello Everyone, and Thanks for this work!
I created a small project which uses Laraberg as editor so users can create posts... You can find it among my projects:
https://github.com/mehranabi/laravel-laraberg
Really appreciate any notice on mistakes in using Laraberg from Author and Contributers which really know how to do it :)

**Comment by mauricewijnia** [comment]
Looks good @mehranabi!

**Comment by Grawl** [comment]
just checked demo from @mehranabi and it works. we can use it in our dashboards now!

**Comment by mauricewijnia** [comment]
Demo is now live at [demo.laraberg.io](http://demo.laraberg.io/)

**Comment by Grawl** [comment]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/846774/57699300-cabdfa80-769a-11e9-980b-3c51f115bcda.png">

just found a bug with grid

**Comment by Grawl** [comment]
I address this as VanOns/laraberg-demo#1
