### ISSUE TITLE
Server Side Custom Block

### ISSUE THREAD

**Issue by maulikbavishi22** [VanOns/laraberg#202]
Hi Team

I am trying to create server side custom block. I did following stuff.
1) 

> config/laraberg.php

```
'blocks' => [
        'my-custom-block' => [
            'render_callback' => 'App\Http\Controllers\MyBlock@render',
            'title' => 'My Custom Block',
            'icon' => 'admin-comments'
        ]
    ],
```
2) Created MyBlock Controller

```
class MyBlock extends Controller
{
    public function render(Request $request)
    {
        // Access block attributes from $request->attributes
        $title = $request->attributes->get('title');

        // Fetch data for the block if needed
        $data = ['Test user 1', 'Test user 2', 'test user 3'];

        return view('site.my-custom-block', compact('title', 'data'));
    }
}
```

3) Created view 

> views/site/my-custom-block.blade.php

<div>
    <h2>{{ $title }}</h2>
    @if ($data)
        <ul>
            @foreach ($data as $item)
                <li>{{ $item }}</li>
            @endforeach
        </ul>
    @endif
</div>

Still i can not see custom block in the editor. 
FYI : I am initializing the editor using following `Javascript : Laraberg.init('test_editor', options)`

Can you please tell me what i am missing here?

**Comment by mauricewijnia** [comment]
Hi!

`render_callback` expects a callable, you're just providing a string. In this case this should probably work:

```
'blocks' => [
        'my-custom-block' => [
            'render_callback' => [App\Http\Controllers\MyBlock::class, 'render'],
            'title' => 'My Custom Block',
            'icon' => 'admin-comments'
        ]
    ],
```

Keep in mind that you're using a controller class for this block which is probably not what you'd want to be using since it's not really a controller in the way that most Laravel developers would see a controller.

Hope this helps!
