### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Sartoric** [VanOns/laraberg#22]
I've enabled translation but it seems that some part are not taken into consideration.
Especially block name.

Since I've found this : https://github.com/WordPress/gutenberg/issues/5410
I guess this is not really a laraberg bug, but I suppose it's more related to gutenberg.js
Do you know on which version it is based on ?

Maybe someone already faced it and knows what to do. 

Suggestion :) maybe an option for locale code set could be added to the **init** function

**Comment by mauricewijnia** [comment]
I believe GutenbergJS is based on Gutenberg v4.8.0 however, Gutenberg consists of multiple packages, all with their own version. I'm not sure what package the issue you linked to is referring to and I'm also not sure what version that package has in Gutenberg v4.8.0.

Translations is definitely on the todo list though, Laraberg uses some custom strings itself so I'll pick this up as soon as I can find some time :)
