### ISSUE TITLE
laraberg dont have featured image, tags, permalink in document tab why?

### ISSUE THREAD

**Issue by zibayii** [VanOns/laraberg#24]
laraberg:
![laraberg](https://user-images.githubusercontent.com/38751445/58365743-cfc24b80-7edd-11e9-9a80-05f91da85653.png)
gutenberg:
![gutenberg-wordpress](https://user-images.githubusercontent.com/38751445/58365751-de106780-7edd-11e9-97fc-36a11c2603ed.png)
laraberg dont have featured image, tags, permalink in document tab why?

**Comment by mauricewijnia** [comment]
The cool thing about Laravel is that you can add those features yourself :)

**Comment by bagusindrayana** [comment]
**"that you can add those features yourself"** as i know from https://developer.wordpress.org/block-editor/developers/slotfills/plugin-document-setting-panel/ you can add new panel in document setting with some line React jsx code, is Laraberg have make some **"helper"** with js/php to add panel or menu easily?

**Comment by mauricewijnia** [comment]
I'd definitely accept a pull request that implements such functionality!
