### ISSUE TITLE
Input tag in Sidebar doesn't understand any type attribute except text

### ISSUE THREAD

**Issue by JunaidQadirB** [VanOns/laraberg#25]
I want to add a field to the Laraberg sidebar, a select in this case.

**Steps To Reproduce**

1. Add a `textarea` tag with an `id` attribute of `body`

```html
<textarea id="body" name="body" rows="50" hidden></textarea>
```

2. Initialize Laraberg with `sidebar` option set to `true`

```javascript
document.addEventListener('DOMContentLoaded',  function () {
    	Laraberg.init('body',
        {
            minHeight: '500px',
            laravelFilemanager: true,
            sidebar: true,
	})
})
```

3. Add `input` markup inside a `div` with class name `laraberg-sidebar`
4. Chnage `type` from `text` to `date`

```html
<div class="laraberg-sidebar">
  <input id="article-title" type="text" name="title" placeholder="Title" />
</div>
```

5. Reload the page

**Expected Behavior**

The `input` date field should appear in the sidebar of Laraberg

**Current Behavior**

Nothing appears in the sidebar

**Env/Version Info**

Laravel: `5.8.*`

Laraberg: `0.0.4@beta`

OS: `Ubuntu 19.04`

Browsers: Firefox, Chrome

**Comment by mauricewijnia** [comment]
Like mentioned in the documentation this is only supported for text, textarea, select, checkbox and radio inputs for now.
