### ISSUE TITLE
Sidebar should be custimizable

### ISSUE THREAD

**Issue by JunaidQadirB** [VanOns/laraberg#26]
At the moment the sidebar can be either enabled or disabled.
As I add fields to the sidebar, I want the panel title to reflect the purpose. Also if someone clicks the `Unpin from toolbar` the sidebar disappears for good. The only way to get it back is to clear the localStorage. 

There should be a way to 
- Change title of the sidebar panel
- toggle back the sidebar 
- disable/hide the `Unpin from toolbar`

**Comment by mauricewijnia** [comment]
I agree, thanks for the suggestion!

**Comment by bhhaskin** [comment]
Even better would be to edit the document sidebar along with adding the custom sidebar.
