### ISSUE TITLE
Custom blocks

### ISSUE THREAD

**Issue by ilic993** [VanOns/laraberg#27]
Hello folks, first of all THANK YOU for porting the only good thing from wordpress into our favorite framework :D

I am still testing laraberg, trying yo figure out my way through it. I managed to create a custom block but there is no any wiki info on the fields for custom block. I see that it is referring to gutemberg wiki but I quite can't figure out how should I write it. In gutemberg we use ACF to make the fields but what should we do with laraberg? Can we get a little more details about this?

Thank you!

**Comment by mauricewijnia** [comment]
Custom block development (without ACF) is documented pretty well in the Wordpress documentation [here](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/writing-your-first-block-type/) and all over the internet. All the Wordpress components you want to use for your block are available as usual at `wp.components`.

Once you've created your custom block you can register it to the editor, this is explained in the README.

For storing data you can use the block's attributes like intended and [documented](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/introducing-attributes-and-editable-fields/) by Wordpress.

**Comment by ilic993** [comment]
@mauricewijnia Thank you for pointing me out, it really helped me a lot. Although I can not figure out how to store the data from the fields I created.

**Comment by mauricewijnia** [comment]
First you have to add the field as an attribute to your block:
```
const MyBlock = {
    title: 'MyBlock',
    icon: 'universal-access-alt',
    category: 'my-category',
    edit: edit,
    save: save,
    attributes: {
        content: { type: 'string' },
    }
}
```

Then you have to create an input that handles that attribute:
```
function edit(props) {
    function updateContent(event) {
        props.setAttributes({ content: event.target.value})
    }

    return <input type="text" value={props.attributes.content} onChange={updateContent}/>
}
```
This way the data gets stored in the block's output.

**Comment by ilic993** [comment]
Not sure where to place that code since whatever I do I get some errors. But I managed to make it work like this: https://paste.ofcode.org/e8GjeGGteqFLHLHG64eHTp

How can I read this data I stored in my view?

Thanks a lot!

**Comment by mauricewijnia** [comment]
A block has 2 functions: `edit()` & `save()`.
The edit function determines how your block looks when it's inside of Gutenberg.
The save function determines how you block looks when it's being displayed in your view.
So in order to show the attribute value you have to show it using the save function:

```
save: function (props) {
  return el("h1", null, props.attributes.blockValue);
}
```

**Comment by ilic993** [comment]
@mauricewijnia Thank you. It does work as intended now you cleared things up a lot. My (I hope) last question would be: how hard would it be to create a repeater field with text input and text area, as well as media upload button?

**Comment by mauricewijnia** [comment]
That shouldn't be too hard, as long as you use the MediaUpload component from `wp.editor`.
Documentation on that can be found [here](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/media-upload).

**Comment by ilic993** [comment]
@mauricewijnia What about repeater fields?

**Comment by cre-mer** [comment]
@ilic993 What does the error say?
