### ISSUE TITLE
Stop relying on front/gutenberg-js

### ISSUE THREAD

**Issue by slaFFik** [VanOns/laraberg#28]
`front/gutenberg-js` author will deprecate it, see https://github.com/front/gutenberg-js/issues/32#issuecomment-497333673

That lib is also based on Gutenberg 4.7, while we already have Gutenberg 5.8.

**Comment by mauricewijnia** [comment]
Laraberg will probably start using Gutenberg packages directly in a future release

**Comment by mauricewijnia** [comment]
The GutenbergJS dependency was removed in version 0.0.7

**Comment by mikebronner** [comment]
@mauricewijnia  Thanks for the update! Will update my nova-gutenberg package and get it integrated there as well. :)

**Comment by mauricewijnia** [comment]
@mikebronner Good stuff! Let me know if you run into any issues :)
