### ISSUE TITLE
Using Laraberg in Vue

### ISSUE THREAD

**Issue by mikebronner** [VanOns/laraberg#29]
When using Laraberg in Vue, I have the problem that each time I run init for a different field without having a completely new response, I get about 59 JavaScript errors, saying that the blocks are already registered:
```
Block "core/paragraph" is already registered.
```

Is there any way to re-init Laraberg with our doing a page refresh?

Thanks!

**Comment by mikebronner** [comment]
Looks like this is essentially the same issue as here: https://github.com/front/gutenberg-js/issues/30

**Comment by mikebronner** [comment]
I was able to work around this problem by doing the following in my Vue component:
```js
    created: function () {
        window.Laraberg.editor = null;
        window.wp = null;
    },
```

Is this the proper solution, or is there a better way you would recommend?

**Comment by mauricewijnia** [comment]
I think this is an issue with Wordpress' Gutenberg package. I'm planning to remove the GutenbergJS dependency and start using the core Gutenberg package directly, so maybe I can find a way around this issue. However, I have a feeling that this won't be easy to solve...

Are you sure that your solution works?
I haven't tried that myself, but I think by using this method only the last editor that you initialise will work correctly.

**Comment by mikebronner** [comment]
Right, it won't work with multiple Gutenberg fields on the same page. But if you only have one Gutenberg field on a page in Vue, it seems to work. :)

Looking forward to the revamp!

**Comment by mikebronner** [comment]
Closing this for now, as the intended issue was resolved. Having multiple fields on the same page is a separate issue we can look into when removing the `gutenberg-js` dependency?

**Comment by nsrosenqvist** [comment]
Hey, sorry to resurrect this issue, I've been trying to run Laraberg from within or wrapped as Vue Component but I just can't get the editor to initialize as it should, I can only get it to run on an element if including the scripts exactly per the README instructions. @mikebronner do you have an example project or an article I could refer to?

**Comment by Cranavvo** [comment]
When using Laraberg in an SPA AngularJS application the first page to load the editor and it's content sticks whenever you transition betweens routes even when the textarea has different content to render inside it.

**Comment by mikebronner** [comment]
@nsrosenqvist Check out if my usage helps you: https://github.com/genealabs/nova-gutenberg. Good luck!

**Comment by nsrosenqvist** [comment]
Thanks a lot guys! That's really helpful!
