### ISSUE TITLE
laraberg Install problem

### ISSUE THREAD

**Issue by phamdoanw** [VanOns/laraberg#3]
I encountered an error while installing into a new project. my version laravel 5.5.45, php version 7.0.33
`D:\laragon\www\Xb>composer require van-ons/laraberg

  [InvalidArgumentException]
  Could not find a version of package van-ons/laraberg matching your minimum-stability (stable). Require it with an e
  xplicit version constraint allowing its desired stability.
require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
`

**Comment by mauricewijnia** [comment]
Hi!
This is happening because Laraberg's stability level is still set to 'dev'.
You can solve your issue by adding this to your composer.json:
```json
"minimum-stability": "dev",
"prefer-stable": true
```
