### ISSUE TITLE
Document Available Init Options

### ISSUE THREAD

**Issue by mikebronner** [VanOns/laraberg#30]
I would love to learn more about the available init options. Could you document what they are, or where to learn more about them? Thanks! :)

**Comment by mauricewijnia** [comment]
I'm not sure what init options you are talking about, all the available options are documented throughout the readme.
I could add a small section that describes the options object and all it's possible properties all in one place though.

**Comment by mikebronner** [comment]
I was thinking about the init options:
```js
Laraberg.init("field_name", options);
```

It's unclear which options can be passed in, and also if these options get passed on to Gutenberg, and if so, which options they also accept. :) Thanks for all your work on this package!

**Comment by mauricewijnia** [comment]
Done!
