### ISSUE TITLE
Use Spatie Laravel Medialibrary instead of Laravel File Manager

### ISSUE THREAD

**Issue by mpanius** [VanOns/laraberg#31]
Spatie Laravel Medialibrary (https://github.com/spatie/laravel-medialibrary) is feature reach, with structured media collections, can be used for video/files uploading/transcoding. It would be great to use it as main medialibrary for Laraberg

**Comment by mauricewijnia** [comment]
Maybe I'm wrong but as far as I know Spatie's Medialibrary does not have a frontend component right?
I'm not sure if Laraberg should be in charge of handling files, the reason I chose to use Laravel Filemanager is so users can still configure the way files are handled themselves.

**Comment by cre-mer** [comment]
Spatie's Media Library does have a front-end component, and I was looking for config to use it instead of the current file manager. The current file manager is indeed great structured but I'm facing too many issues with it. It does not seem to be stable

**Comment by swiderskimarcin** [comment]
What about this library https://github.com/ctf0/Laravel-Media-Manager ?
