### ISSUE TITLE
Multiple Instances Of Gutenberg On The Same Page

### ISSUE THREAD

**Issue by mikebronner** [VanOns/laraberg#32]
This might be worth looking into once the `gutenberg-js` dependency is dropped?

**Comment by mauricewijnia** [comment]
Yes definitely, although I'm afraid that Gutenberg is storing a lot of state in the `window.wp` object. So we will probably have to find a way to work around that

**Comment by mauricewijnia** [comment]
That's what I was thinking as well. I'll have to look into how Gutenberg references the objects internally though, I think it will be difficult if it accesses `window.wp` directly.

**Comment by erralb** [comment]
Hi, have you found a solution for this?
I would like to create a Gutenberg ACF field type, so it would need multiple instances

**Comment by mikebronner** [comment]
Unfortunately not yet ... I will be looking into updating to the latest Gutenberg version over the next few weeks, as my need for this is becoming more critical as well.

**Comment by erralb** [comment]
@mauricewijnia Seems like it's possible: https://github.com/WordPress/gutenberg/issues/20590

**Comment by mauricewijnia** [comment]
@erralb Ah that's good news! I'll have a look at it.

Sadly it's really busy at work at the moment, so it looks like I will not have time until later this month...

**Comment by erralb** [comment]
@mauricewijnia no worries, just wanted to let you know. I'll keep you updated if I'm going forward with my ACF field type!

**Comment by mirkojvc** [comment]
Hello guys what's the status on this one? It would be awesome if multiple editors could be possible. :)

**Comment by christianmagill** [comment]
@erralb Did you ever make any progress on this?

**Comment by filipac** [comment]
i really want this too :( trying to implement but stuck for the moment

**Comment by vijayrana-99** [comment]
Did anybody find the solution for multiple laraberg instance on the same page?

**Comment by superipey** [comment]
@vijayrana-99 see my PR on @VanOns/block-editor: https://github.com/VanOns/block-editor/pull/5 to add multiple block editor in one page
