### ISSUE TITLE
Unauthenticated exception

### ISSUE THREAD

**Issue by ilic993** [VanOns/laraberg#33]
Seems like I am doing something wrong and it would be of real help if someone could point me out to my mistake.

I have an custom auth guard:
`'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],`

Which I am using in the laraberg:
`'use_package_routes' => true,`
 ` 'middlewares' => ['web', 'auth:admin'],`
 ` 'prefix' => 'laraberg'`

Thing is, everything works like a charm but when I enter debug in VSCode and click on a block in laraberg I get an error like this:
https://i.imgur.com/9Isprpx.jpg

It does not quite make a problem but still I don't like errors in my projects :D
Thank you.

**Comment by mauricewijnia** [comment]
Seems like Laraberg requests are not sending all the information that your middleware needs.
Could you capture a request that does pass your custom guard and the laraberg block request and paste the headers of both of those requests here?
