### ISSUE TITLE
Click on element after unselect make it disappear

### ISSUE THREAD

**Issue by Epistol** [VanOns/laraberg#37]
**Describe the bug**
Adding an image on the block image, then clicking on the "Insert from URL" after closing it a first time close the block until you click again on the place it's supposed to be.

**To Reproduce**
1. Go to the insert post
2. Click on insert image
3. Click on "Insert From Url"
4. Click outside
5. Try to click on "Insert From Url again"

**Expected behavior**
Close the block (or is hidden ?).

**Screenshots**

**Environment (please complete the following information):**
- Laraberg Version: 
 - OS: macOS
 - Browser : Chrome
 - Version @dev

**Additional context**
Got some errors : 
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of PopoverDetectOutside which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

**Comment by mauricewijnia** [comment]
What version of Laraberg does this apply to? I can't seem to reproduce it. Will close the issue until it's reproducable.
