### ISSUE TITLE
Gutenbergable trait error on table containing column called content

### ISSUE THREAD

**Issue by Ceepster14** [VanOns/laraberg#39]
I've come across an issue whilst attempting to implement Laraberg in a Laravel Backpack project using their PageManager add-on (https://github.com/Laravel-Backpack/PageManager). I'd written an Observer on their 'pages' table so that when a page gets created or updated I could use the observer to trigger a **lb_content** call from the Gutenbergable trait to updated the Laraberg tables. Whenever this happened a **call to a member function setContent() on string** error gets thrown in the setLbContentAttribute method in the trait.

I tracked the issue down to the fact their pages table (on which I'd applied the Gutenbergable trait) contains a column called 'content' which overrides the $this->content in the method.

**To Reproduce**
1. In a Laravel project, create a table containing a column called 'my_content'
2. Create a Model for the table and apply the Gutenbergable trait to the model
3. Create a new instance of the model, set the my_content field to contain some suitable content and save the instance
4. Use lb_content from the trait to update the Laraberg tables
5. Everything works as expected
6. Rename the column from 'my_content' to 'content'
7. Create a new instance of the model, set the content field to contain some suitable content and save the instance
8. Use lb_content from the trait to update the Laraberg tables
9. The following error gets thrown

![laraberg_error](https://user-images.githubusercontent.com/6481512/61730872-35ae4080-ad72-11e9-9f28-9d0f76726011.JPG)

I know I can get round the issue by rewriting the PageMaker add-on to use a different column name, but given the usefulness of Laraberg in replacing other editors in other CMS style systems, it's possible that this issue might occur elsewhere. 

Any thoughts as to another way to remedy the issue?

**Comment by mauricewijnia** [comment]
The content object should get a more distinguished name, it's only accessed by Gutenbergable methods so this shouldn't be a problem. 

Until this is fixed you can try to modify the Gutenbergable trait code and change the name of the `content` function to something like `laraberg_content` and replace all instances of `$this->content` to `$this->laraberg_content`. I'm not entirely sure if that would work though.

**Comment by Ceepster14** [comment]
Hi,

Thanks for that - I did in fact do just what you suggested and it appears to the holding up!

Cheers

Chris
