### ISSUE TITLE
Filemanager

### ISSUE THREAD

**Issue by jacofda** [VanOns/laraberg#4]
Hello there,
first thank you for integrating Gutenberg in Laravel. I got it up an running in no time.
Now I am trying to add Laravel File Manager, but without success. It opens the default URL no matter what I insert as prefix. 

`Laraberg.initGutenberg('[id_here]', { laravelFilemanager: { prefix: '/[lfm_prefix_here]' } })`

Any advice?

Thank you in advanced

**Comment by SimplyThomas** [comment]
https://github.com/VanOns/laraberg/blob/ab250842818491a4a46bf83a581a4c093cd2fa79/src/resources/js/laravel-filemanager/laravel-filemanager.js#L33

It does not look like `lfmOptions` is getting passed down to `lfmListener` function, so this line never runs?

The `lfmOptions` constant is scoped to the `setupLaravelFilemanager` function, so the `lfmListener` function would return `undefined` in that if statement.

@jacofda, this looks like a bug and not user-error.
