### ISSUE TITLE
Edit Existing Model

### ISSUE THREAD

**Issue by el-profesor-nadir** [VanOns/laraberg#40]
I add Laraberg to an existing model. when i edit the model i receive this error :

Trying to get property 'raw_content' of non-object  

i think because there is no relation between my model and the Content model.

So i create a simple function 

public function hasContent()
    {
        return $this->content ? true : false;
    }

and to edit :
<textarea class="form-control" id="description" name="description" rows="30" hidden>{{ $region->hasContent() ? $region->lb_raw_content : null }}</textarea>

**Comment by mauricewijnia** [comment]
Issue will be fixed in the next release!
