### ISSUE TITLE
Object(...) is not a function init.js line 29

### ISSUE THREAD

**Issue by perryborst** [VanOns/laraberg#41]
I get a javascript error when initializing the editor: Object(...) is not a function in init.js

**To Reproduce**
1. Fresh install of Laraberg on Laravel 5.6 project, migrate and publish files
2. Add dependencies
3. Add textarea to view: <textarea id="laraberg_content" name="my_content"></textarea>
4. Add init call: Laraberg.init('laraberg_content');

**Expected behavior**
I was expecting to see the editor :)

**Screenshots**
![Screenshot 2019-07-31 at 14 35 40](https://user-images.githubusercontent.com/7968190/62212252-a4a61d80-b3a0-11e9-920a-7f4f591b64b1.png)

**Environment:**
- Laraberg Version: "van-ons/laraberg": "^1.0@RC"
 - OS: Mac OSX 10.14.5
 - Browser [ff, chrome, safari]
 - Version [ff: 68.0.1, Chrome: 76.0.3809.87, safari: 12.1.1 

**Additional context**
I tried three times with different projects but get the same outcome. Maybe I just missed something :(

**Comment by mauricewijnia** [comment]
I get the same error when using react version 16.6.3.
Can you see if it goes away if you use 16.8.6?
```
  <script src="https://unpkg.com/react@16.8.6/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/moment@2.24.0/min/moment.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
```

**Comment by perryborst** [comment]
Well there's you're problem :) Thank you for your quick reply, this works!

I will close this issue... thank you for putting this package online! 

greetings from Amsterdam :)
