### ISSUE TITLE
Remove mention of Wordpress in code

### ISSUE THREAD

**Issue by FlusherDock1** [VanOns/laraberg#42]
First, I want to say thanks from the entire October CMS community for your work.

I have a small question. Are you planning to remove the mention of "WP:" in the content code?

**Comment by mauricewijnia** [comment]
Can you give me some examples of places where `wp` is used in the code that could be removed?

**Comment by FlusherDock1** [comment]
![image](https://user-images.githubusercontent.com/20070837/62409604-c0990180-b5e2-11e9-8926-5565a7984a34.png)

Example on your demo page, place any block and go to the code editor. This comments always contain wp placeholders. And then this comments coming to production from Laraberg.

**Comment by mauricewijnia** [comment]
That's the place where Gutenberg stores data like block names and attributes, if those get removed the editor will stop working completely...
