### ISSUE TITLE
Error When Toggling Custom Blocks

### ISSUE THREAD

**Issue by mikebronner** [VanOns/laraberg#46]
I'm getting the following error when click Options > Custom Fields:

```
TypeError: null is not an object (evaluating 'document.getElementById("toggle-custom-fields-form").submit')
```

Is this something on my end, or is that part not implemented just yet?

Thanks! :)

**Comment by mauricewijnia** [comment]
Ah this is not implemented, and I don't think it ever will be since custom fields are a very WordPress specific feature that don't really make any sense in a Laravel environment. I'll make sure to remove it before the next release :)

**Comment by mikebronner** [comment]
@mauricewijnia Thanks!

**Comment by mauricewijnia** [comment]
Removed the options menu in v1 since it wasn't serving any purpose
