### ISSUE TITLE
Initialization of packages 

### ISSUE THREAD

**Issue by FlusherDock1** [VanOns/laraberg#47]
**Describe the bug**
Webpack throwing errors when I'm trying to run `npm run watch`

**To Reproduce**
1. Clone or download rep in any folder.
2. Open the terminal and run `npm i`
3. then `npm run watch`
4. Get errors because of unknown Gutenberg packages.

**Expected behavior**
Run `npm run watch` without errors

**Screenshots**
One of the erorrs:
![Снимок экрана 2019-08-07 в 16 44 11](https://user-images.githubusercontent.com/20070837/62627737-a3da3200-b932-11e9-994c-4165b4956f62.png)

**Environment:**
- Laraberg Version: 1.0.0-rc.1
 - OS: macOS Mojave 10.14.5
 - Browser: –
 - Version: –

**Comment by mauricewijnia** [comment]
You have to link the gutenberg repository through npm.

You can do that by cloning the repository git@github.com:WordPress/gutenberg.git
To get the packages that laraberg currently uses you have to checkout v6.2.0:
`git checkout v6.2.0`
Then `npm install` followed by `npm run build` and finally `npm link`

After that the gutenberg packages will be available.

**Comment by FlusherDock1** [comment]
Thanks for the quick response! But I still get errors...

My steps:
1. In cloned Laraberg rep. executing `git clone https://github.com/WordPress/gutenberg.git gutenberg` 
2. then `cd gutenberg; git checkout v6.2.0; cd ..`
3. then `npm install; npm run build; npm link;`

![Снимок экрана 2019-08-07 в 17 36 50](https://user-images.githubusercontent.com/20070837/62631769-f3702c00-b939-11e9-9277-8c6d6f9e09a0.png)

Do i need to move gutenberg folder to node_modules folder? 

p.s. Sorry if I'm doing something obvious wrong

**Comment by mauricewijnia** [comment]
Ah sorry I forget the last step...
You should run `npm link gutenberg` in the Laraberg project folder

**Comment by FlusherDock1** [comment]
I did everything 3 times to be more precise...

Cloned repo, cloned Gutenberg, executed steps above. and...

![Снимок экрана 2019-08-07 в 17 52 10](https://user-images.githubusercontent.com/20070837/62633044-303d2280-b93c-11e9-8196-6f087d5599eb.png)

**Comment by mauricewijnia** [comment]
Hmm strange, `npm link gutenberg` should create a symbolic link to the gutenberg package in your laraberg's `node_modules` folder, are you seeing that?

**Comment by FlusherDock1** [comment]
> are you seeing that?
Yes, and the arrow represents a symbolic link.

![Снимок экрана 2019-08-07 в 17 59 57](https://user-images.githubusercontent.com/20070837/62633663-31228400-b93d-11e9-8033-321d985e5c61.png)

**Comment by FlusherDock1** [comment]
Tried `npm ls gutenberg`, and `npm ls "random package from package.json"`

![Снимок экрана 2019-08-07 в 18 03 39](https://user-images.githubusercontent.com/20070837/62633975-c02f9c00-b93d-11e9-9c35-c6e14b65df1a.png)

**Comment by mauricewijnia** [comment]
I just cloned laraberg into a new repository and did:
`npm install`
`npm link gutenberg`
`npm start`

And I'm not getting the error you're getting...
So I'm not really sure what's going on, but I don't really know how to help you.
My npm version is 6.9.0 and my node.js is version 10.16.0.
Maybe a different version is causing those issues?

**Comment by FlusherDock1** [comment]
> Are you sure Gutenberg is building successfully?

What do you mean? 

> And I'm not getting the error you're getting...

I just read all manuals how to link package and after around 10 attempts of reinstalling.
And now I'm doing 

`npm ls gutenberg`

![Снимок экрана 2019-08-07 в 18 50 03](https://user-images.githubusercontent.com/20070837/62637479-2d463000-b944-11e9-93f6-f4b6b75f9a3d.png)

But when I do `npm start` everything stays the same...

**Comment by FlusherDock1** [comment]
God. I just figured all out. 

My first steps were wrong, and after your 
> Are you sure Gutenberg is building successfully?

I left the project for the night, and in the morning I tried everything with a fresh mind.

I did not build Gutenberg. I did not link package inside Gutenberg folder by 'npm link'.

I think you don't have any errors because you already linked Gutenberg in your `/../lib/../node_modules`, and you can link it to project without building it.


**Finalizing all steps to get all work properly:**

1. Clone Laraberg rep.
2. Clone Gutenberg rep. in Laraberg folder:
`git clone https://github.com/WordPress/gutenberg.git gutenberg`
3. After cloning execute these commands:
    ```bash
    cd gutenberg           // go to Gutenberg folder
    npm i                  // install all dependencies
    npm run build          // Build Gutenberg
    sudo npm link          // Link it to your global node_modules 
    cd ..                  // Go back to Laraberg root
    npm i                  // install all dependencies
    npm link gutenberg     // Link Gutenberg package to Laraberg
    ```
4. Now you can work with Laraberg.

**Comment by mauricewijnia** [comment]
Ah nice!
This is what I meant in my first comment, guess I just wasn't clear enough.
Glad you got it to work :)
