### ISSUE TITLE
Prevent saving content in lb_contents if parent model was not saved

### ISSUE THREAD

**Issue by IsraelOrtuno** [VanOns/laraberg#49]
As of now, whenever I update my model attribute `lbContent`, the content in the `lb_contents` table is saved, even if I didn't save the parent model. I consider this a bug.

The expected behaviour should be to update the `lb_contents` content once the primary model has been saved (created or updated). Same happens when deleting a model, it's bound to the `deleting` event, and if for some reason, other event cancels the deletion, the `lb_content` content will be lost.

I would like to know if this was intentional for some reason and if you would consider a PR to fix this issue and standardize the reactions to the events.

**Comment by mauricewijnia** [comment]
Hi!

This is not really intentional and I guess it's like this because of a lack of Laravel experience from my side, I'll definitely consider a PR that fixes this :)

**Comment by IsraelOrtuno** [comment]
Super, will start working on it right now ;D

Thanks for making such an effort!
