### ISSUE TITLE
Translate Laraberg Manually

### ISSUE THREAD

**Issue by ahorazahedi** [VanOns/laraberg#51]
Hi!
I need to translate Laraberg for my project but i didn't find the strings ...where do you store strings

**Comment by mauricewijnia** [comment]
There's nothing setup for translating currently, but 99% of all strings will be coming directly from Gutenberg and I believe those should be translated already?

**Comment by Basdl76** [comment]
@mauricewijnia but how can we "activate" the translations?

**Comment by mauricewijnia** [comment]
Hmm maybe I was wrong, I can't seem to find any of the translation files in the Gutenberg repository. It uses the i18n package for translations which takes files in a .jed format.
https://www.npmjs.com/package/@wordpress/i18n
I won't have time this week to look into this, but i'll definitely take a pull request or provide help in some other way :)

**Comment by Sartoric** [comment]
Based on some (very basic :D) investigation on Gutenberg I come up with this solution.

I've made a custom js that I call inside the "laraberg" page 

```
<script src="{{ asset('js/laraberg-translation.js') }}"></script>
```

laraberg-translation.js
```
import translations from '<JSON FILE PATH>';
wp.i18n.setLocaleData(translations);
```

the Json file is a common i18n dictionary file

**Comment by tpaksu** [comment]
Also waiting for this :) +1

**Comment by OusManDiouf** [comment]
Hi, could you give us some guidelines on how to translate the plugin ( without any custom blocks) with the help of 
the @wordpress /i18n package ? how to get translatable strings? etc ... any help would be welcome

**Comment by SquallX** [comment]
Hi,

Somebody have the JSON files to make manually translation ?

Thx

**Comment by tpaksu** [comment]
Gutenberg uses some strings from WordPress translation files, which you can download from http://api.wordpress.org/translations/core/1.0/ (wordpress uses that url to define which zip file to download), then you should convert those translations to JED file translation format to use with tannin javascript translation package.. I was tinkering with it last year, that's what I can remember.. HTH to someone. I dropped using it.

**Comment by helveden** [comment]
Hello i try JED and 

import translations from '<JSON FILE PATH>';
wp.i18n.setLocaleData(translations);

but not working for me.

**Comment by rezahmady** [comment]
I did what you said. But I make this error in console
Can you tell me what to do?

``TypeError: Cannot read properties of undefined (reading 'setLocaleData')``
@Sartoric

**Comment by Sartoric** [comment]
> I did what you said. But I make this error in console Can you tell me what to do?
> 
> `TypeError: Cannot read properties of undefined (reading 'setLocaleData')` @Sartoric

Well, this workaround is 3 years old. Probably something changed in Gut meanwhile :)
