### ISSUE TITLE
Getting "Your site doesn't include support for the block" Error 

### ISSUE THREAD

**Issue by JunaidQadirB** [VanOns/laraberg#52]
I'm getting this "Your site doesn't include support for the block" when I save the content.

Steps to reproduce the behaviour:
1. Set the content to the model 
```php
$model->lb_content = request('body');
$model->save();
```
2. View the content in the laraberg editor
```php
<textarea id="laraberg">{{$model->lb_content}}</textarea>
```

**Expected behaviour**
The content should be saved without any extra markup.

**Screenshots**

![Screenshot from 2019-08-30 14-15-07](https://user-images.githubusercontent.com/642353/64009252-f58c6b80-cb30-11e9-9db8-77d09382a1f2.png)
![Screenshot from 2019-08-30 14-15-15](https://user-images.githubusercontent.com/642353/64009253-f6250200-cb30-11e9-9c38-d35e32c9d7d5.png)
![Screenshot from 2019-08-30 14-15-23](https://user-images.githubusercontent.com/642353/64009255-f6bd9880-cb30-11e9-8a1b-d66273a2135b.png)

**Environment (please complete the following information):**
- Laraberg Version: dev-master (As of August 30, 2019)
 - OS: Ubuntu 19.04
 - Browser Firefox

**Comment by mauricewijnia** [comment]
You should use the raw content to intialize your editor like as described in the readme:
```
<textarea id="laraberg">{{$model->lb_raw_content}}</textarea>
```

**Comment by JunaidQadirB** [comment]
Thanks.

**Comment by vijayrana-99** [comment]
Anyone getting this error for version 2?
