### ISSUE TITLE
Does Laraberg support server side rendering for custom blocks? 

### ISSUE THREAD

**Issue by Arsyad** [VanOns/laraberg#57]
Hi, 

This isn't a bug report but more of a clarification. I am trying to create custom blocks and wonder if Laraberg supports server side rendering / dynamic blocks like WordPress?

I want to create a custom block where it will show depending on a users logged in status and profile settings. 

Is that possible? 

I am thinking one way after a model is fetched, I can parse the raw blocks content and modify from there before it's being output on front-end, but not sure if this is best practice.

**Comment by mauricewijnia** [comment]
Currently Laraberg does not support serverside/dynamic blocks.
However, someone is trying to implement it right now, so hopefully we'll have it soon! :)

**Comment by Arsyad** [comment]
Thank you for sharing that information. Will keep a look out on the updates!
