### ISSUE TITLE
After update to 1.0.2 I lost my reusable blocks

### ISSUE THREAD

**Issue by Piastra91** [VanOns/laraberg#59]
Hi guys,

I've updated laraberg from 1.0.1 to 1.0.2. After the update inside the menu block, there isn't the voice "reusable blocks". Inside the table lb_blocks on DB there are all my reusable blocks. 
I fixed it with add new "reusable block" and copy the old content to the new. 
I forgot some passages after update?

Also if I create new page, I don't see the reusable block menu but only inside the page where I create them.

Thanks,
Matteo

**Comment by mauricewijnia** [comment]
Hi Matteo,

Thanks for reporting this issue!
We've had this problem before, back then it was a problem with Gutenbergs' middleware.
I'll see if I can look into this and release a fix this week :)

**Comment by mauricewijnia** [comment]
Fixed in 1.0.3!

**Comment by skacco** [comment]
Hello I have the same problem, could you share with me the fix? What have you changed? I don't find this fix on git log of 1.0.3 versione
when I create new page, I don't see the reusable block menu but only inside the page where I create them.
