### ISSUE TITLE
After update to 1.0.2 Uncaught js errors

### ISSUE THREAD

**Issue by Piastra91** [VanOns/laraberg#60]
Hi guys,

After the update to 1.0.2 I have these errors in my console:
![Schermata 2019-10-07 alle 10 47 42](https://user-images.githubusercontent.com/9450429/66297497-12fee300-e8f0-11e9-97c2-d9db57461ed4.png)

Is there a way to fix it?

Thanks! :)
Matteo

**Comment by mauricewijnia** [comment]
Those errors are the reason you're not seeing your reusable blocks anymore, so once reusable blocks are fixed those errors will disappear :)

Thanks for reporting!

**Comment by Piastra91** [comment]
@mauricewijnia best support ever! Thank you! Waiting for the fix :)

**Comment by chiragsenjaliya** [comment]
@Piastra91 @mauricewijnia   I am still getting this error on the new version is it fixed?
