### ISSUE TITLE
Allow other file managers

### ISSUE THREAD

**Issue by newelement** [VanOns/laraberg#62]
Hello, I'm working on a project and have built a file manager that supports TinyMCE and CKEditor and would love to support this project as well, but it looks like LFM is only supported.

**Comment by mauricewijnia** [comment]
It's out of scope for this project to support all different filemanagers out there, i'm sorry.
You can take a look at the `laravel-filemanager/index.js` file to get an idea of how to implement a different media library though. Hope that helps!
