### ISSUE TITLE
laravel filemanager 6.x update breaks laraberg

### ISSUE THREAD

**Issue by tpaksu** [VanOns/laraberg#63]
The laravel-filemanager dev-master branch seems to be changed a lot and the file/image selections don't work in laraberg, because now they pass an object instead of url/path tuple as the `window.opener.setURL` callback arguments. 

https://github.com/UniSharp/laravel-filemanager/blob/78aeffe12087b1ba43cdbd5e48385bb0e5221b0e/public/js/script.js#L193-L198

and laraberg is using this line to get the images:

https://github.com/UniSharp/laravel-filemanager/blob/78aeffe12087b1ba43cdbd5e48385bb0e5221b0e/public/js/script.js#L599

The fix is needed for people using Laravel 6.X because the laravel-filemanager package has the change on the Laravel 6.X update. The fix should be applied [here](https://github.com/VanOns/laraberg/blob/8709ea0e61b0fac52e29ba7257a03ed57434174b/src/resources/js/laravel-filemanager/index.js#L26-L35):

https://github.com/VanOns/laraberg/blob/8709ea0e61b0fac52e29ba7257a03ed57434174b/src/resources/js/laravel-filemanager/index.js#L26-L35

But I couldn't compile the javascript with the included webpack configuration.

**Environment**
- Laraberg Version: 1.0.3
 - OS: Windows
 - Browser: Opera (Chromium)
 - Version 63.0.33x

**Additional context**
Testing with Laravel 6.3 on Laragon, PHP 7.3, nginx with php-fpm running, laravel-filemanager dev-master branch

**Comment by JMoralSquare1** [comment]
Hi!!
Any update about this? thanks! ;)

**Comment by tpaksu** [comment]
@JMoralSquare1 I fixed all and added some new things in my own fork if it. This seems like abandoned.

**Comment by JMoralSquare1** [comment]
@tpaksu , thanks I will take a look ;)

**Comment by tpaksu** [comment]
> @tpaksu , thanks I will take a look ;)

Sorry I forgot to mention, the code is in the lfm-fix branch.

**Comment by hvlucas** [comment]
Any update or workaround for this issue?

**Comment by LonnyX** [comment]
@JMoralSquare1 did you take a look on the fix? We are still waiting and it's a breaking change

**Comment by jam1e** [comment]
> > @tpaksu , thanks I will take a look ;)
> 
> Sorry I forgot to mention, the code is in the lfm-fix branch.

How would I go about using your fix in my project?
I seem to be having issues with requiring in your fork of this package.

**Comment by tpaksu** [comment]
@jam1e since I continued developing on that branch, I didn't register it to packagist, you can fork it and register it yourself, but before forking you can try it by [adding the fork in your composer.json file](https://stackoverflow.com/a/13500676/916000).

**Comment by LonnyX** [comment]
> @jam1e since I continued developing on that branch, I didn't register it to packagist, you can fork it and register it yourself, but before forking you can try it by [adding the fork in your composer.json file](https://stackoverflow.com/a/13500676/916000).

@tpaksu I just tried your branch and it seems that the fix doesn't works... Are you sure it's fixed?

**Comment by tpaksu** [comment]
@jam1e can you try with this file manager? It's a fork of unisharp one. I don't know what I've changed but these two should work. 

https://github.com/tpaksu/laravel-filemanager

**Comment by LonnyX** [comment]
@tpaksu Even with your fix, it doesn't works :/ Maybe this should stay Open until it's fixed by the team.

@mauricewijnia please check this

**Comment by tpaksu** [comment]
@LonnyX  I don't know, I gave up to work on laraberg but left the repositories open in case someone needs some code about localization, but at where I left, it should be working. Maybe it needs a rebuild on gutenberg to get working again, I don't know. I'll leave it open then.

**Comment by MuhammadTaha** [comment]
it doesn't work with laravel 5.8 as well
