### ISSUE TITLE
No way to change editor placeholder

### ISSUE THREAD

**Issue by JunaidQadirB** [VanOns/laraberg#64]
By default Laraberg displays `Write your story` as the placeholder but there seems no way to override it.

![Screenshot from 2019-10-24 23-33-38](https://user-images.githubusercontent.com/642353/67514742-c6b8ee80-f6b6-11e9-916b-406085342374.png)

**Expected behaviour**
When initializing the editor or by setting the `placeholder` attribute on the `textarea` tag, one should be able to override the default placeholder text.

**Environment:**
- Laraberg Version: 1.0.3
 - OS: Ubuntu 19.04
 - Browser Firefox
 - Version 70.0

**Comment by ArtMin96** [comment]
```javascript
titlePlaceholder: 'Add title',
bodyPlaceholder: 'Body placeholder'
//... Other settings
```
