### ISSUE TITLE
No way to remove a block

### ISSUE THREAD

**Issue by Jacotheron** [VanOns/laraberg#67]
**Describe the bug**
Having looked at the real Gutenberg, I am unable to find any way to remove a block that is no longer needed. 

**To Reproduce**
1. Create any block
2. Attempt to delete it - no delete option on the dropdown of the 3 dots button, or anywhere in the interface ()

**Expected behavior**
I expected to be able to remove unwanted blocks

**Screenshots**

**Environment (please complete the following information):**
- Laraberg Version: 1.0.3
 - OS: Windows
 - Browser Firefox
 - Version (latest)

**Comment by amenk** [comment]
Press DELETE or Backspace works :)

**Comment by andreas83** [comment]
@amenk that's true, but  some customer of mine asked the same question too. 

so is there an easy way to add delete function to dropdown menu? 
i guess the function is already there, it "just" need to be triggered somehow. 

![image of gutenberg dropdown](https://social.codejungle.org/upload/5e4bbd71d889b0.33345186_Screenshot_20200218_113257.png)

**Comment by kylethomas-dev** [comment]
It is there, its set to display:none.  Inspect the code and you will see it. Perhaps you can change this with some CSS or within the files somewhere? Below is a screenshot of my setup, with the display:none removed, I just did it with chrome inspect tools.
<img width="1079" alt="Screen Shot 2020-04-05 at 9 06 11 pm" src="https://user-images.githubusercontent.com/55139370/78473127-82f80400-7781-11ea-9c6f-50047011b6bb.png">

**Comment by adeguntoro** [comment]
> It is there, its set to display:none. Inspect the code and you will see it.
Can you show it to me which line / code i need to edit ? Front-end is not my thing.

**Comment by spaantje** [comment]
Just add this to your styles: 
```css
.components-popover__content div .components-menu-group:last-of-type {
	display: block !important;
}	
```
