### ISSUE TITLE
Dynamic Blocks

### ISSUE THREAD

**Issue by Sartoric** [VanOns/laraberg#70]
I'm wondering if is there a way to use "dynamic blocks" in laraberg.
I'm a bit stuck looking for a way to set the render_callback

**Additional context**
https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/

**Comment by mauricewijnia** [comment]
Currently there is no way to add dynamic blocks, it definitely is something I would like to add. But it's gonna take a lot of work and sadly I don't have that much time to work on this project.

I will gladly accept a pull request that implements this feature though!
