### ISSUE TITLE
VUE SPA Multiple Blocks Already Registered when returning to component.

### ISSUE THREAD

**Issue by kinger251285** [VanOns/laraberg#72]
**Describe the bug**
First of All thank you for adding this project.

I am using in a VUE component and have the Gutenberg working as it should. However if i click to another component (page), dashboard for instance and then return to the Gutenberg page, my entire project crashes and have the following errors:

Block "core/paragraph" is already registered
Block "core/image" is already registered.
Block "core/heading" is already registered.

etc (59 in total)

Ive tried Mike Bronner's page reload and numerous browser refresh solutions but none work. However when i refresh when on another component then i can return to the Gutenberg with no errors.

**Comment by kinger251285** [comment]
Figured a small workaround to reload the page.

This is now working and allowing me to go between components.

`mounted: function () {
       if (window.Laraberg.editor != null) {
            window.parent.location.reload(false);
            // window.Laraberg.editor = null;
            // window.wp = null;
        } else {
          Laraberg.init('content');
        }
    },`

**Comment by happyDemon** [comment]
reloading the page was out of the question for me, I thought unmounting the editor shouldn't be too hard.

Basically in my Vue component's beforeDestroy hook, I wanted to place this:

```js
// Remove react
window.wp.element.unmountComponentAtNode(window.Laraberg.editor);

// Remove container element
const elem = document.getElementById("laraberg__editor");
elem.parentNode.removeChild(elem);
```

This didn't work out too great since only the DOM got unmounted, the second time a laraberg instance is initialized it toggles the `welcomeGuide` and `fullscreenMode` features (meaning they're turned on now) and re-registers all block types.

This makes it impossible to re-init, I personally wanted to use this in Nova, but this is a blocker.

@VanOnsNL kijken jullie er naar? Of stuur ik een PR?

**Comment by happyDemon** [comment]
small update, found a solution that works for me.

When your Vue component gets unmounted/destroyed, try to run the following code:

```js
	  // Remove any active blocks
      const blocks = window.wp.data.select('core/blocks').getBlockTypes().map(bt => bt.name);
      const {removeBlockTypes} = window.wp.data.dispatch('core/blocks');
      removeBlockTypes(blocks);

      // Toggle these on again
      const { toggleFeature } = window.wp.data.dispatch('core/edit-post')
      toggleFeature('welcomeGuide')
      toggleFeature('fullscreenMode')

      // Start teardown
      const {__experimentalTearDownEditor} = window.wp.data.dispatch('core/editor');
      __experimentalTearDownEditor();

      // Unmount component
      window.wp.element.unmountComponentAtNode(window.Laraberg.editor);
```

Still feels very hackish to me though, couldn't really find another solution at this moment.

**Comment by mikebronner** [comment]
@happyDemon Thanks for this! This helped me with some annoyances: https://github.com/GeneaLabs/nova-gutenberg/blob/master/resources/js/components/FormField.vue#L16
