### ISSUE TITLE
Clicking „Add block" triggers HTTP 401 Error

### ISSUE THREAD

**Issue by alexander-schreiner** [VanOns/laraberg#73]
**Describe the bug**
Clicking „Add block" triggers HTTP 401 error on site with HTTP Auth

**To Reproduce**
1. GET Request a site with HTTP Authentication
2. Authenticate yourself with correct credentials
3. Navigate to a site with Laraberg initialized on it
4. Click on the button „Add block" (if it doesn't work on the first try, try a second time)
5. Receive a HTTP 401 Error, eventhough you authenticated yourself in Step 1

**Expected behavior**
Laraberg background requests should not trigger HTTP 401 Errors 
Possible Solution: The requests should be made using the credentials previously provided 

**Screenshots**
![screen](https://user-images.githubusercontent.com/42301971/71421152-6e33ac80-2679-11ea-84d0-6264a722d6b9.PNG)

**Environment (please complete the following information):**
- Laraberg Version: [1.0]
 - OS: [Windows 10 Home, Version 1903]
 - Browser [Chrome]
 - Version [Version 79.0.3945.88]

**Additional context**
The HTTP Auth is implement like the following (NGINX):
server {
	# (...) There is other configuration in the previous lines
	auth_basic "Administration";
	auth_basic_user_file /etc/nginx/.htpasswd;
}

**Comment by alexander-schreiner** [comment]
Temporary fix could be to whitelist all request to `/laraberg*` in the webserver config.

**Comment by shubham-y** [comment]
Remove middlewares or add your custom middleware in [laraberg.php](https://github.com/VanOns/laraberg/blob/master/src/config/laraberg.php)
`

        'use_package_routes' => true,
        
        'middlewares' => [],

        'prefix' => 'laraberg',

        "models" => [
            "block" => Block::class,
            "content" => Content::class,
        ],
        

`
