### ISSUE TITLE
How to change the editor paragraph default font size

### ISSUE THREAD

**Issue by ngocviet** [VanOns/laraberg#77]
**Is your feature request related to a problem? Please describe.**
Currently, there're predefined font sizes in the editor. It is mismatched with the style on my article result. Is there a way to configure the font size steps?
![font_size](https://user-images.githubusercontent.com/236093/74653778-744a9300-51bb-11ea-8f24-a4c81c44d728.PNG)

**Describe the solution you'd like**
If it needs development please point me the direction I could try to help and make pull request.

**Additional context**
Laravel version: 6.0
Laraberg version: 1.0.3

**Comment by mauricewijnia** [comment]
As far as I'm aware this is the way the default paragraph block works.
If you need other functionality you could try creating a custom block that works they way you want.

The README should help you get started on creating and registering your custom blocks
