### ISSUE TITLE
Question: How Can I Add new field under document?

### ISSUE THREAD

**Issue by ellemaker** [VanOns/laraberg#78]
![Screenshot_39](https://user-images.githubusercontent.com/4677416/74890231-6d3fa280-53be-11ea-957d-33e388f3c090.png)

**Comment by jam1e** [comment]
From reading the README, I came to the conclusion that you must enable the sidebar option when initialising laraberg, then anything within a div with a class of laraberg-sidebar would show up here. I can't seem to display anything other than what you have shown in this image.

Have you followed these steps too?

**Comment by ellemaker** [comment]
> From reading the README, I came to the conclusion that you must enable the sidebar option when initialising laraberg, then anything within a div with a class of laraberg-sidebar would show up here. I can't seem to display anything other than what you have shown in this image.
> 
> Have you followed these steps too?

yes, it will add a custom field on the sidebar but not under the "Document" tab.

**Comment by mauricewijnia** [comment]
As said by others, you can add fields to the Laraberg sidebar, the README.md explains how you can do this.
