### ISSUE TITLE
Block "Gallery", "Cover" and "Media & Text" and laravel-filemanager bug

### ISSUE THREAD

**Issue by slaxxarn** [VanOns/laraberg#8]
When using laravel-filemanager and laraberg you cannot use files from the filemanager for blocks "Gallery", "Cover" and "Media & Text" because when inserting media, you try to find the element with class ".editor-media-placeholder__url-input-container" and this element don't exists for those blocks.

Mabye this is not implemented yet but just wanted to report it.

**Comment by mauricewijnia** [comment]
Thanks for reporting!
The filemanager implementation was a bit sketchy, so fixing that also fixed this issue in https://github.com/VanOns/laraberg/commit/3a443d9d03b2b9b57b10ac92cc8f5894477e3b41
