### ISSUE TITLE
getContent as Json

### ISSUE THREAD

**Issue by catalinux** [VanOns/laraberg#81]
Hi,

Is there a way I can get the content of the editor as json and not a generated markup?

So instead of geting

```
<!-- wp:paragraph -->
<p>asdasd</p>
<!-- /wp:paragraph -->

<!-- wp:my-namespace/my-block -->
<h1>Hello saved content</h1>
<!-- /wp:my-namespace/my-block -->
```

I would get a list of blocks

```json
[
  {
    "type": "paragraph",
    "value": "My paragraph"
  },
  {
    "type": "wp:my-namespace/my-block",
    "value": {
      "firstName": "John",
      "lastName": "Doe"
    }
  }
]

**Comment by mauricewijnia** [comment]
WordPress uses the `parse_blocks()` function to achieve this.
You could take a look at their WP_Block_Parser class to see how they do this.

https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-block-parser.php

Feel free to create a pull request if you end up creating a solution for this :)
