### ISSUE TITLE
Laraberg with swappable front-end editor

### ISSUE THREAD

**Issue by JunaidQadirB** [VanOns/laraberg#83]
Laraberg, the Laravel package is a nice package, I wish I could use an editor of my choice instead of Gutenberg.

**Describe the solution you'd like**
I want to be able to use any editor I like, either by changing a config or creating a custom driver.

**Comment by mauricewijnia** [comment]
Haha this is interesting, the sole purpose for Laraberg has always been to make Gutenberg easily usuable in Laravel.

What part of Laraberg is it that you would like to use with other editors?

**Comment by JunaidQadirB** [comment]
Yes, I do understand. I like the whole `back-end` of it. It gives me flexibility to add content to any model via the `Gutenbergable` trait. Maybe I don't make sense but I felt this need more than one :).

**Comment by mauricewijnia** [comment]
Might be a good idea for a different side project haha!
