### ISSUE TITLE
when uploading image in filemanager it show blank and empty alt attribute

### ISSUE THREAD

**Issue by weerowee** [VanOns/laraberg#84]
**Describe the bug**
When uploading image it only show white/blank pics and when i select it, it show empty alt attribute . its the same issue in demo site.

**To Reproduce**
1. Go to filemanager
2. upload image

**Expected behavior**
It suppose to show preview image and when click should show picture

**Screenshots**
<img width="893" alt="Screen Shot 2020-03-28 at 15 18 49" src="https://user-images.githubusercontent.com/58925154/77816702-2608a800-7108-11ea-8b27-6ba9ed45ac23.png">

**Environment (please complete the following information):**
- Laraberg Version: [e.g. 1.1.1]

**Comment by mauricewijnia** [comment]
Hi!

It looks like Laravel Filemanager now takes the base url from your APP_URL in the .env file, so you should set that to the base url of your website.

Also make sure that you linked your storage folder, and that the owner of the storage folder is the owner as your other publicly accessible files.
