### ISSUE TITLE
Can not get jQuery appended data in Laraberg.getContent()

### ISSUE THREAD

**Issue by priyankpateltrootech** [VanOns/laraberg#85]
Hi there,

I have used jQuery to append some data into the editor. and when I'm trying to get the data using Laraberg.getContent. I get it empty.

Could you please suggest how can I get it or is it even possible?

Thanks in advance.

**Comment by mauricewijnia** [comment]
You can append data by getting the content first, append your data to it, and then setting the content to the result of that:

```js
const content = Laraberg.getContent() + yourData
Laraberg.setContent(content)
```
