### ISSUE TITLE
No navigation block

### ISSUE THREAD

**Issue by kylethomas-dev** [VanOns/laraberg#87]
I have successfully got Laraberg to work with a local project, however, I noticed the Navigation block is missing. Is there a way to successfully add this block in?

Thanks,

Kyle
<img width="1169" alt="Screen Shot 2020-04-05 at 9 04 14 pm" src="https://user-images.githubusercontent.com/55139370/78473064-06fdbc00-7781-11ea-8bcd-18aa4d3f8e0a.png">

**Comment by mauricewijnia** [comment]
The navigation block is a block from WP core, so it's not part of the Gutenberg project.
