### ISSUE TITLE
Media Manager Support

### ISSUE THREAD

**Issue by kylethomas-dev** [VanOns/laraberg#88]
I am using Maelstrom CMS to develop my project.
Larabergis up and running, but I noticed the only supported Media Manager is Laravel Filemanager.
Maelstrom CMS includes a basic media manager, could this be used with Laraberg?
https://www.maelstrom-cms.com/components/media-manager.html#media-manager
If so, how could I integrate this? Any help would be greatly appreciated.

Thanks,

Kyle

**Comment by newelement** [comment]
I opened #62 in hopes this might happen one day.

**Comment by mauricewijnia** [comment]
It's out of scope for this project to support all different filemanagers out there, i'm sorry.
You can take a look at the laravel-filemanager/index.js file to get an idea of how to implement a different media library though. Hope that helps!
