### ISSUE TITLE
Unexpected Error - Editor Crash

### ISSUE THREAD

**Issue by kylethomas-dev** [VanOns/laraberg#89]
The editor is getting an unexpected error and crashing, this error is on both the Laraberg demo (demo.laraberg.io) and my local install.

To reproduce:
- Click the 'Add Block' button within the editor.
- Type in name of the block e.g. 'Paragraph'
- Now remove your search term using backspace (delete on mac)
- Once the last character has been removed the error will appear

I have included a screenshot and error code below. It seems to me that the delete function is attempting to delete something it shouldn't or cannot and throwing an error, once all characters are removed.

`Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at Eg (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:123:398) at ni (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:128:421) at ui (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:133:152) at https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:158:377 at unstable_runWithPriority (https://unpkg.com/react@16.8.6/umd/react.production.min.js:27:36) at Vc (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:158:360) at Sc (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:158:144) at Z (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:156:492) at https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:217:89 at Xe (https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js:23:368)`

<img width="1259" alt="Screen Shot 2020-04-06 at 10 13 20 am" src="https://user-images.githubusercontent.com/55139370/78513544-cdb06500-77ef-11ea-8c2f-657f556ba4f3.png">

**Comment by mauricewijnia** [comment]
Seems to be fixed with Gutenberg 8.1.0
