### ISSUE TITLE
Not null violation: 7 ERROR: null value in column "contentable_id" 

### ISSUE THREAD

**Issue by emexxRepo** [VanOns/laraberg#9]
Hello 
Im using postgreSql

MYcode ---

> $rawContent = Contract::find(1);
>         if (empty($rawContent)) {
>             $contract = new Contract();
>             $contract->mycontent = "TestCon";
>             $contract->save();
>             $rawContent = Contract::find(1);
>         }
> 
>         $model = new Contract();
>         $model->setContent($rawContent,true);

i have a problem while i am saving raw content throw below error
"
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "contentable_id" violates not-null constraint DETAIL: Failing row contains (9, null, null, App\Contract, null, page, 2019-04-30 09:45:19, 2019-04-30 09:45:19). (SQL: insert into "lb_contents" ("contentable_id", "contentable_type", "updated_at", "created_at") values (, App\Contract, 2019-04-30 09:45:19, 2019-04-30 09:45:19) returning "id")

"

help me

**Comment by mauricewijnia** [comment]
I'm not exactly sure what you're trying to do here but this should work if you're trying to create a new 'Contract':
`
$contract = new Contract();
$contract->setContent("TestContent", true);
$contract->save();
`
Hope that helps, and good luck!

**Comment by JunaidQadirB** [comment]
So do I other fields like this?
```php
$contract = new Contract();
$contract->setContent("TestContent", true);
 $contract->field1='Value1'; //Additional field defined in the Contracts model
$contract->save();

```

**Comment by JunaidQadirB** [comment]
```php
$contract->save();
```

should be called before 

```php
$contract->setContent("TestContent", true);
```

**Comment by JunaidQadirB** [comment]
> I'm not exactly sure what you're trying to do here but this should work if you're trying to create a new 'Contract':
> 
> ```
> $contract = new Contract();
> $contract->setContent("TestContent", true);
> $contract->save();
> ```
> 
> Hope that helps, and good luck!



> I'm not exactly sure what you're trying to do here but this should work if you're trying to create a new 'Contract':
> 
> ```
> $contract = new Contract();
> $contract->setContent("TestContent", true);
> $contract->save();
> ```
> 
> Hope that helps, and good luck!

```php
$contract->save();
```

should be called before 

```php
$contract->setContent("TestContent", true);
```
