### ISSUE TITLE
Vue js Laraberg integration

### ISSUE THREAD

**Issue by mirchoz** [VanOns/laraberg#91]
Thank u for your efforts, fantastic project. 

I would ask you if it's possible, if you could make a small tutorial on how to use Laraberg in Vue Js project.

Thank you in advance.

**Comment by mauricewijnia** [comment]
Laraberg just replaces a textarea input element. You can get the content by calling a function thats explained in the readme. There's nothing Vue specific that you have to implement.

**Comment by AmirrezaNasiri** [comment]
@mirchoz I've made a Vue.js package for editor part of Laraberg: [evryn/laraberg-vue](https://github.com/evryn/laraberg-vue)
You can examine its example project if you want to know more: [evryn/laraberg-vue-example](https://github.com/evryn/laraberg-vue-example)
