### ISSUE TITLE
Laraberg.getContent issues - adds post.php?post=1&action=edit to the end of URL

### ISSUE THREAD

**Issue by kinger251285** [VanOns/laraberg#92]
Hi

I have laraberg working in another project and decided to use in my latest project. I am trying to get the content from the laraberg and as the documents using the recommended function but this is throwing issue. 

When the below code runs the last part of my URL is removed and this is added - post.php?post=1&action=edit.

``this.editedItem.content = Laraberg.getContent();``

Any help appreciated.

**Comment by kinger251285** [comment]
Project where it is still working as per docs is using laraberg version 1 and non working is version 1.1

**Comment by mauricewijnia** [comment]
Thanks for letting us know!
I'll take a look at this as soon as I can find some time :)
