### ISSUE TITLE
HTTP 500 Error - Column Not Found 1054 Unknown column 'laraberg_content' || When New content added to model, no error when content exists || Laraberg Version 1.1

### ISSUE THREAD

**Issue by kinger251285** [VanOns/laraberg#93]
I have a store and update methods in my controller (in Laravel). Both have identical ways of updating the data as per documentation.

`$Model = Model::findOrFail($id);`

`$Model->lb_content = $Content;`
        
`$Model->save();`

In the store method when i run this it generates a http 500 error - column not found 1054 Uknown column 'laraberg content'. The data is added to the database but then breaks the rest of my controller code for the store method.

With the update method it works fine, updates the content and no error thrown. 

I am setting the content in both cases using the below:

`
this.editedItem.content = Laraberg.getContent();
`
So therefore it seems if content exists withing the database in the lb_contents table then it updates fine. However if there is no data then the data is added but an error is thrown.

I have used this in another project using version 1.0 and it works fine. I started this new project with version 1.1 and rolled it back via composer to version 1.0. Could possibly now be some conflict?

I am using Laravel version 6.18.15 and Vue.js.

**Comment by mauricewijnia** [comment]
Unless you can reproduce this with a clean install of Laraberg I'm affraid I can't really help you.

**Comment by kinger251285** [comment]
> Unless you can reproduce this with a clean install of Laraberg I'm affraid I can't really help you.

Ive just removed the package via composer and then added as version 1.1 and this seems to be fixed.
