### ISSUE TITLE
Clickable Block Content Area Not Full size || Can fix appearance with CSS but not clickable || Version 1.1 Laraberg

### ISSUE THREAD

**Issue by kinger251285** [VanOns/laraberg#94]
**Describe the bug**
I Have the gutenberg rendering. The whole box is full size (with border) however the editable content area is not. I can fix this with css making the area the height i want. However that area when modified is not clickable as should be. Only the top content box is. Please see screen shot below:

![image](https://user-images.githubusercontent.com/44111958/82902961-267ebd00-9f58-11ea-808e-7f4b0ac5c433.png)

**Comment by mauricewijnia** [comment]
Please use the ticket templates to report issues like this. Your title says it's v1.1 but this looks like a way older version.
